### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by Pozzdamm** [jwstegemann/fritz2#114]
Would be conceivable to develop a parser, which inspect a html-site written with html, js and css to  suggest codelines in fritz2?

**Comment by jwstegemann** [comment]
You can reuse any css in your fritz2-project by adding your css file(s) to the resource-folder and include a link into your html.

I would think, that translating - for example a jquery based approach to a reactive on would be really complex.

It should be not to difficult though to write a small app translating existing html into kotlin code using the fritz2-dsl. Would you mind trying ;-)

**Comment by jamowei** [comment]
@Pozzdamm like @jwstegemann sad you can try to build some parser on your own. But currently our API may change in future until we reached version 1.0. Keep that in mind. ;-)
For now we are both very busy with stabilize and improve the fritz2 core and therefore don't have the time to build something like this. If you have any further question please open a new issue.
