### ISSUE TITLE
Support web-sockets in remote

### ISSUE THREAD

**Issue by Luftzig** [jwstegemann/fritz2#116]
**Is your feature request related to a problem? Please describe.**
I would like to communicate with a backend that uses websockets, and flows seem to lend themselves nicely to that.

**Describe the solution you'd like**
```kotlin
val socket = remote("ws://server/ws").websocket() {
  // transform frames here
} handledBy update

// In other places:
store.data.bind() // Render incoming data
socket.send(message) // Send a message
```

**Describe alternatives you've considered**
I am still unfamiliar with fritz2, but as an alternative I think that I could use `window.fetch` and bind to the events.

**Comment by jwstegemann** [comment]
Thank you. I will be able to have a closer look at it next week. Will come back to you with a first draft.

**Comment by Luftzig** [comment]
Can you give me an outline of where you would like this the go? I have a partially working solution, which is partially mostly because my backend doesn't work as expected.
I think I can dumb down my whole project to create a Ktor full-stack with WebSockets example, if that's helpful.
