### ISSUE TITLE
Concatenate Strings in two (or more?) Flows

### ISSUE THREAD

**Issue by fritzmaster2** [jwstegemann/fritz2#161]
allow this
```kotlin
val x: Flow<String> ...
val y: Flow<String> ...

val z = x +y
```

meaning, that when x = "A" at a given point in time and y = "B" z would be "A B".

**Comment by jamowei** [comment]
Hi, you can do it with the following global extension function:
```kotlin
operator fun Flow<String>.plus(other: Flow<String>): Flow<String> = this.combine(other) { v1, v2 -> "$v1 $v2" }
```

**Comment by jamowei** [comment]
We don't think that this functionality should be provided by fritz2.
