### ISSUE TITLE
add options for integrated component-styling

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#169]
A separate model should be added that offers functionality to make it easier to style your components in Kotlin. While this is not necessary when using a css-framework like bootstrap, it is a foundation for fritz2-bases component libs.
Feature needed are

- create static css from kotlin
- create dynamic css from kotlin (using dynamic parameters from a component for example)
- offer a system of parameters and a DSL to easily add the most relevant styling options to your components
- support for theming and theme-switching

**Comment by hpehl** [comment]
I like the idea. However we shouldn't try to re-implement CSS in a Kotlin DSL. Basic support for creating CSS in Kotlin is a good thing, but it's certainly difficult to decide where to draw the line. IMO CSS is best developed in CSS files. Most frameworks already come with CSS files (HTML boilerplate, Bootstrap, ...). 

In our project we added support to better handle CSS classes defined in external CSS files. ATM CSS classes are just concatenated strings passed to the `baseClass` parameter. This gives room for improvements. Here's some code we use to improve this:

```kotlin
inline fun classes(builderAction: ClassBuilder.() -> Unit): String = ClassBuilder().apply { builderAction() }.build()

fun classes(vararg classes: String): String = classes.joinToString(" ")

class ClassBuilder {

    private val builder = StringBuilder()

    operator fun String?.unaryPlus() {
        this?.let {
            builder.append(it).append(" ")
        }
    }

    infix fun String.`when`(condition: Boolean): String? = if (condition) this else null

    fun build() = builder.toString().trim()
}
```

Using this we can dynamically build the list of CSS classes in our components:

```kotlin
class Dropdown(val text: String, rightAlign: Boolean, up: Boolean) : Div(baseClass = classes {
    +"pf-c-dropdown"
    +("pf-m-right-align" `when` rightAlign)
    +("pf-m-up" `when` up)
})
```

I don't request to use our approach. Just some food for thoughts.

**Comment by jwstegemann** [comment]
@hpehl: This looks great.

What I am not sure is, how this would work with parameters on more general components. For example if you want to set a certain margin or a certain color when using the component, etc. And while doing so you would want to stay inside the rails of your style system.

Maybe you could have a look at https://github.com/jwstegemann/fritz2-styling

It is very early work in progress, I would be very happy to get your thoughts on it...

**Comment by hpehl** [comment]
> Maybe you could have a look at https://github.com/jwstegemann/fritz2-styling

Looks very sophisticated and goes way beyond what Im doing. I need some time to look into it, before I can give feedback.
