### ISSUE TITLE
Question: Why is AttributeDelegate declared internal?

### ISSUE THREAD

**Issue by eiswind** [jwstegemann/fritz2#173]
First thanks for this great work. I have been playing with pretty similar ideas a while ago and I'm very happy to see what you have created.

I try to create a kotlin adapter for a custom element.
I followed your ideas at https://docs.fritz2.dev/WebComponents.html
 and I found that AttributeDelegate is declared as internal ( so unfortunately I cannot use it).

Another question would be how I could handle properties (vs. attributes)

**Comment by jwstegemann** [comment]
We just had no use case for AttributeDelegate outside the fritz2-core. Will open it up in 0.8. Is this ok for you (first snapshots will be available end of next week)?
I am not sure, if I get what you mean with "how I could handle properties". Do you have a short example available?

**Comment by eiswind** [comment]
Of course, I'm just prototyping no hurries.
As for the properties, that did work out with a copy of ValueAttributeDelegate, so this is fine now too.

**Comment by jwstegemann** [comment]
We have reworked the way attributes are set. To be more flexible we now use overridden methods at the corresponding text like `disabled(true)` or `disabled(someFlowOfBoolean)`. This way it should also be easy to handle attributes in different ways.
