### ISSUE TITLE
Paging support for QueryRepositories

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#177]
We need some special Repository that supports Paging out of the box and manages the current page state.

**Comment by hpehl** [comment]
FWIW I'm currently developing a port of [PatternFly](https://www.patternfly.org//) using fritz2. It comes with different data components which also support paging. It might be a different use case, but feel free to take a look:

- code: https://github.com/patternfly-kotlin/patternfly-fritz2
- showcase code: https://github.com/patternfly-kotlin/patternfly-fritz2-showcase
- showcase demo: https://patternfly-kotlin.github.io/patternfly-fritz2-showcase/#home

The paging is basically implemented by the classes [`Items<T>` and `PageInfo`](https://github.com/patternfly-kotlin/patternfly-fritz2/blob/master/src/commonMain/kotlin/org/patternfly/Item.kt#L91) and the store [`ItemStore<T>`](https://github.com/patternfly-kotlin/patternfly-fritz2/blob/master/src/jsMain/kotlin/org/patternfly/Item.kt).

**Comment by jwstegemann** [comment]
repositores have been removed from fritz2 with version 1.0-RC2
