### ISSUE TITLE
Using multiple checkboxes (input()) with a single store does not work correctly

### ISSUE THREAD

**Issue by EvaBS** [jwstegemann/fritz2#182]
**Description**
Using multiple checkboxes (input()) with the same boolean Store does not work correctly. Each checkbox that is clicked once is excluded from check status changes afterwards. The HTML input tag however does correctly add and remove the "checked" attribute when the store's state changes.

**How To Reproduce**
1. Create multiple checkboxes using the fritz2 input function, but use the same boolean Store for all the checkboxes. I used an input component function for testing. It has no label as it does not change the reported behavior:

```kotlin
fun HtmlElements.checkboxTest(
    checked: RootStore<Boolean>,
    id: String? = null,
) {
    div(id = id) {
        style = const("margin: 10px")
        input(id = "$id-input") {
            type = const("checkbox")
            checked.data.bindAttr("checked")
            changes.states() handledBy checked.update
        }
    }
}
```

2. In main, create the checkboxes and some visualization of the store's state. I also made an extra button to change the store's state without checking a checkbox.

```kotlin
div {
    val checkedTestStore = RootStore(false)
    checkboxTest(
        id = "check10",
        checked = checkedTestStore
    )
    checkboxTest(
        id = "check11",
        checked = checkedTestStore
    )
    checkboxTest(
        id = "check12",
        checked = checkedTestStore
    )
    checkboxTest(
        id = "check13",
        checked = checkedTestStore
    )
    checkboxTest(
        id = "check14",
        checked = checkedTestStore
    )
    checkboxTest(
        id = "check15",
        checked = checkedTestStore
    )
    div {
        checkedTestStore.data.map {
            p { +"checked: $it" }
        }.bind()
        checkedTestStore.data.map { checked ->
            input {
                value = const("change checkstate")
                type = const("button")
                clicks.map {
                    !checked
                } handledBy checkedTestStore.update
            }
        }.bind()
    }
}
```

3. Start the app. 
4. Pick ONE checkbox (let's call it Fred) and click it multiple times. You should see the store's state change each time. If you look at the browser's console, you can see that ALL input tags get the attribute "checked" each time you click, like expected.
5. Do not restart the app or reload the page. Pick another checkbox (let's call it George) and click it multiple times. You should notice that Fred does not longer change its state like the other checkboxes, but if you look at the console, you can see that the attribute "checked" is still correctly placed in the input tag. If you pick yet another checkbox and click it, George will not change state anymore either. Using the button to change the store's state will not alter this behavior.

**Expected Behavior**
All checkboxes should check and share the same check state, visually and in HTML.

**Machine**
 - Desktop
 - OS: Win10
 - Browser: Chrome, Opera

**Additional context**
Using multiple checkboxes with just one value store does not have many applications, so this is probably not urgent.

**Comment by jamowei** [comment]
Hi, please try the following:
```kotlin
// instead of
checked.data.bindAttr("checked")
// do this
checked = checked.data
```
Hope this helps!

**Comment by EvaBS** [comment]
Does help, thank you.
