### ISSUE TITLE
Fix troubles when using fritz2

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#183]
We discovered some pitfalls in the fritz2 0.7 API which we want to address in the next releases of fritz2.

## Leaving out `bind()` function
A typically mistake in fritz2 0.7 is to left out the `bind()` function on a `Flow<Tag<E>>` which results in nothing gets rendered:
```kotlin
div {
    activities.each().render { activity ->
        activityCheckbox(activity)
    }.bind() // if left out nothing happens, but no compiler error given
}
```
**Solution**: 
All `render()` functions don't need the `bind()` call anymore.

## Using functions instead of vars for standard HTML attributes
In fritz2 0.7 you can only set a standard HTML attribute by doing this:
```kotlin
input {
    type = const("text") // must create a Flow, instead of using String directly
    
    value = myStore.data // ok
    
    value handledBy myStore.update // throws NotImplementedError
    // instead use the event:
    changes.values() handledBy myStore.update
}
```
In this example you can see some common mistakes you can do in fritz2 0.7 when using the attributes. At first there is an unnecessary boxing of a static `String` to a `Flow<String>` for assigning it to the `type` attribute. Second thing is that it is not allowed to receive the data of an attribute as `Flow` like `value handledBy subStore.update` shows. Therefore you must listen on events that gets fired, when something changes.
**Solution**:
We don't use var assignments anymore instead we create for each standard HTML attribute two functions. The first function is for the native type (e.g. `String`, `Boolean`, `Int`,...) the other function is for a `Flow` of the same type. This also fixes the Issue [#56](https://github.com/jwstegemann/fritz2/issues/56).
```kotlin
input {
    type("text") // native
    value(myStore.data) // flow
    
    // attribute functions return nothing
    value(myStore.data) handledBy myStore.update // compiler error
}
```
## More than one element in `render {}`
At the moment you must pay attention in fritz2 0.7 on returning only one top-level HTML element inside the `render {}` block otherwise a `MultipleRootElementsException` gets thrown. You can't also use a non-exhaustive if-statement for rendering only HTML parts when your condition matches.
```kotlin
render {
    section("header") {
        myStore.data.render {
            if(it > 5) div { ... } // compiler error
        }
    }
    section("main") { // throws MultipleRootElementsException
        ...
    }
}
```
**Solution**
We decided to implement a new version of the default `render {}` function which is a bit slower the the original one but satisfy these requirements. If you don't need this features and have a special case where performance is critical you can use the original function which then is called `renderElement {}` instead.

**Comment by hpehl** [comment]
Really good improvements. I've hit more or less the same issues.
