### ISSUE TITLE
html renders only one child-element

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#21]
calling `html` to build a tree of elements, you can add more than one child to the root-`html` in perfectly valid code. 
Since it is later bound using a `SingleMountPoint` only the last added child is visible in the DOM in the browser, because the others are simply overridden. This is not intuitive.

**Comment by jamowei** [comment]
I think the only possibility to solve this problem is to show an error message in the console, when someone is trying to setup multiple `Tags` in `html {...}` context.
