### ISSUE TITLE
include version in js-file-name

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#22]
To prevent caching-issues in the browser it would be good to include the actual version-number in the name of the js-file.

This requires adjusting the link in index.html automatically.

**Comment by jamowei** [comment]
Can be done by adding this in your `build.gradle.kts` file:
```kotlin
group = "dev.fritz2"
version = "0.8"

tasks.getByName<KotlinWebpack>("jsBrowserProductionWebpack") {
    outputFileName = "${project.name}-${project.version}.js"
}
```
