### ISSUE TITLE
Change default HTML Template in order to make modals work

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#229]
**Describe the bug**
Currently the default HTML Template defines the mount id on the ``body`` tag.
This conflicts with the modal component, because the content of the body tag is replaced by the initial ``mount`` and so the modals div gets removed.

**Suggestion**
- Insert ``div`` as mount target

**Comment by jamowei** [comment]
I think I found a better solution to solve this problem in a more general way and make the modal component independent of static html template. See #249

**Comment by jamowei** [comment]
[Here](https://gist.github.com/jamowei/6b88ce9b8bb6a29731d36eb40886d81e) is my test code.

**Comment by chausknecht** [comment]
Perhaps we could solve the problem with a more general (and better extenable) approach?

Let's recap the main problem: We habe some components (modals and toasts are coming for the 0.9 probably, PR 235) that rely on a *static* position within the DOM. This conflicts with the central mount point of the fritz2 application, which can be freely chosen so that it might *destroy* these DOM nodes at first rendering.

What about mixing the two aspects?

We should try to integrate those *global* DOM subtrees into the fritz2 application's mount target. That way there is no timing problem, nor the html template need to comply with a separating structure as initially proposed by me. All of fritz2's DOM nodes would start from one root node, everything else in the HTML file will remain untouched by fritz2.

We could introduce a *main* component that wraps all other application's elements. This component will initialize those *global* components right before or after the main content:
```kotlin
render(someTheme, "#target") {
    app {
        // built context of the app component; could enable adding / removing some mount points for global components
        content {
            // all other stuff goes here
        }
    }
}
```

- ``app`` will call some *init* function on all "registered" global components, so that they are correctly set up and create their necessary DOM nodes.
- Obviously we can't force the user to use ``app``, but we could recommend this and it remains really simple and easy to remember (we even might deliver this within out template project)
- for really simple showcases or throw away experimentation code one could omit this without harm, so it does not unnecessary clutter running demo code.
- the worst thing if omitting ``app`` is that those global components (modal + toast so far) won't work. But this is not worse than the current situation!
- the good thing is: We can introduce some mechanism for these global components that enables the app to set a marker that the initialization has allready run. Thus enables such an implementing component to throw an exception if its central component setup was not initialized. This would be a huge advantage to other approaches!
- we could create some property in ``app `` that enables the initialization for custom global components (or even disables some), so this remains extensible
- we could use this central component for other sorts of initialization steps in the future
- we should carefully discuss the name. ``app`` is just a first draft; ``components`` fits too and would be explicit about the usage of fritz2's components within an application. Other ideas are welcome!
