### ISSUE TITLE
Wrong compile error in IDE for generated Lenses

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#234]
Sometimes there is an error in your IDE with the generated `L` object after the Gradle build were successfull.
```
val name = inspector.sub(L.Person.name)
```
This is of course confusing and we should try to check if we can tell the IDE where to find this generated sources.

**Comment by sabiou** [comment]
That's exactly the issue i'm facing. my IDE can't find the `L` object.

**Comment by sabiou** [comment]
@jamowei what should you do in this case ? is there any work around ?

**Comment by jamowei** [comment]
I personally don't have the problem. You can try to invalidate caches or use the `gradlew` script instead. If you find something that helps please let us know. Thanks!

**Comment by sabiou** [comment]
did everything from invalidating caches and gradle scripts still the `L` object is not generated.

**Comment by jwstegemann** [comment]
Are you available for a zoom / jitsi session (maybe tomorrow afternoon?) Since we do not have this error on our machines this seems to be the only way to find out, what is different on your's...

**Comment by sabiou** [comment]
yeah sure I'm available. 👍🏽

**Comment by CreatsheR** [comment]
Same problem here. I would also be available and also at working time if you want. Greets Arne

**Comment by jwstegemann** [comment]
@CreatsheR if you drop us a mail at info@fritz2.dev I will send you an invite...

**Comment by jwstegemann** [comment]
Classes annotated with `@Lenses` have to be in the `commonMain` SourceSet (as described here https://docs.fritz2.dev/Lenses.html). Also you should put your data model classes in a package different from root to avoid name conflicts.

We add `commonMain` to our project template to make this more obvious...

**Comment by sabiou** [comment]
Great ! thanks to y'all !

**Comment by cesure** [comment]
I had this problem too. IntelliJ Idea also told me about "duplicate roots detected" and that it fixed it by removing some duplicates. I then started to compare my `build.gradle.kts` with the one from https://github.com/jamowei/fritz2-ktor-todomvc until I found my problem:

```
    jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "1.8"
        }
        withJava() // remove this
    }
```

I had to remove the `withJava()` call and after that IntelliJ Idea didn't complain anymore and it startet to find the generated lenses (after running `gradle jsMainClasses`). I don't even known where I had this from and my project still runs fine in the backend and frontend.

I hope this information can help other people.

**Comment by jamowei** [comment]
> I had this problem too. IntelliJ Idea also told me about "duplicate roots detected" and that it fixed it by removing some duplicates. I then started to compare my `build.gradle.kts` with the one from https://github.com/jamowei/fritz2-ktor-todomvc until I found my problem:
> 
> ```
>     jvm {
>         compilations.all {
>             kotlinOptions.jvmTarget = "1.8"
>         }
>         withJava() // remove this
>     }
> ```
> 
> I had to remove the `withJava()` call and after that IntelliJ Idea didn't complain anymore and it startet to find the generated lenses (after running `gradle jsMainClasses`). I don't even known where I had this from and my project still runs fine in the backend and frontend.
> 
> I hope this information can help other people.

Yes, I had the same problem in this project too. And I also had to remove the `ẁithJava()` call. But then the `run` tasks stopped working and I must changed a more of my build file in order to get it work again.
Now it should work fine without `withJava()`.
Hopefully the current version of `build.gradle.kts` is a good place to take from. 

If you have some improvements please let me know or give me a PR! Thanks
