### ISSUE TITLE
Support querySelecor for global `render` function

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#241]
Currently we use `document.getElementById()` function in fritz2 for selecting the target-element:
```kotlin
fun render(targetId: String, override: Boolean = true, content: RenderContext.() -> Unit) {
    document.getElementById(targetId)?.let { parentElement ->
       ...
    }
}
```
But sometimes there are no `id` attributes to use. That is why the function `document.querySelector()` would be more flexible for selecting the target-element. But we cannot provide both as global `render` function, because the signature would be even.
```kotlin
fun render(targetId: String, override: Boolean = true, content: RenderContext.() -> Unit) {
    document.getElementById(targetId)?.let { parentElement ->
       ...
    }
}
// compiler error
fun render(selector: String, override: Boolean = true, content: RenderContext.() -> Unit) {
    document.querySelector(selector)?.let { parentElement ->
       ...
    }
}
```

**Possible solutions**
1. Use always the `document.querySelector()` instead
2. Add following parameter: `elementProvider: Document.(String) -> Element? = { getElementById(it) }`
```kotlin
fun render(selector: String,
    elementProvider: Document.(String) -> Element? = { getElementById(it) },
    override: Boolean = true, content: RenderContext.() -> Unit
) {
    elementProvider(document, selector)?.let { parentElement ->
        ...
    }
}
```
3. Use different function names

**My personal evaluation**
1. must prepend `#` for id-selection & not the best performance, see [benchmark](https://www.measurethat.net/Benchmarks/Show/2488/0/getelementbyid-vs-queryselector)
2. looks weird when using a different `elementProvider`
3. I have no good idea how to name it?

What do you think?
@hpehl @jwstegemann @chausknecht

**Comment by hpehl** [comment]
I would opt for 

```kotlin
fun render(selector: String, override: Boolean = true, content: RenderContext.() -> Unit) {
    document.querySelector(selector)?.let { parentElement ->
       ...
    }
}
```

which is IMHO the most flexible solution. I can live with the slightly worse performance compared to `getElementById()`.
