### ISSUE TITLE
optimize gradle build

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#25]
gradle build-configuration is full of flaws (sorry, my first gradle-project...):
- redundant dependencies,
- redundant versions, names, etc.
- redundant [insert something else]

This should be streamlined and optimized.

**Comment by jwstegemann** [comment]
added Kotlin-compiler-arguments in #52

**Comment by jwstegemann** [comment]
looks already much better after version 0.5 but still potential:

- transitive jsRun on sub(model)-projects

**Comment by jamowei** [comment]
Currently there are no urgent issue known. Please provide a new specific issue if there are issues with the gradle build.
