### ISSUE TITLE
Add option to close popovers when clicking outside

### ISSUE THREAD

**Issue by haukesomm** [jwstegemann/fritz2#261]
**Current behavior**
Currently a popover can be closed by using it's close-button.

**Enhanced behavior**
An option should exist allowing popovers to be closed when an outside click is registered. This feature may be needed by various projects as it also exists in other frameworks such as Chakra-UI (see [this](https://chakra-ui.com/docs/overlay/popover#customizing-the-popover) example).
This behavior could be disabled by default to not mess-up existing projects.

**Comment by derTranspirator** [comment]
The Component will get two new options (closeOnBlur (default = true) , closeOnEsc (default = true) ) 
If u click or tab  outside the popover or rather use the escape key the popover closed.

The componennte will be use a flow of these events.
