### ISSUE TITLE
Community separation

### ISSUE THREAD

**Issue by mpetuska** [jwstegemann/fritz2#286]
Looking at the readme, I see that you guys have your own discord and even slack workspace. Would it not be better to try and keep the community together by only directing all of it to a single communication channel (preferably on kotlinlang slack, since most kotlin thevs are there anyways, so no new accounts or apps are needed)

Here's the badge to fritz2 channel on kotlinlang slack:

[![Slack chat](https://img.shields.io/badge/kotlinlang-%23fritz2-B37700?logo=slack&style=flat-square)](https://kotlinlang.slack.com/messages/fritz2)

**Comment by jamowei** [comment]
Url for joining the official **kotlinlang** Slack workspace: https://surveys.jetbrains.com/s3/kotlin-slack-sign-up
