### ISSUE TITLE
Enable reactive styling within our DSL sections

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#291]
Currently the styling - especially within components - does not really integrate into the reactive approach of the rest of the framework. To apply dynamic stylings depending on a ``Flow<T>`` is quite cumbersome:

```kotlin
someCoponent({
    // styling block -> currently no reactive coupling possible!
}) {
    className(/* couple a flow to some styling; for example by combining staticStyle + whenever */)
}
```

It would be nice, if we can create a nicer API to achieve this!

Just to present some idea:
```kotlin
someComponent({
    // styling as usual; remains as long as the component lives
    whenever(/* Flow<Boolean> */) {
        // this styling will only be applied if flow emits ``true``
        // will be *removed* if flow change to ``false``
    }
}) {
}
```

Hint: Obviously we need some *mountpoint* for the styling definitions within the DOM.

**Comment by metin-kale-cf** [comment]
reactive styles are possible using classes:

    box({
        children("&.selected") {
            background { color { gray100 } }
        }
    }){
        classList(/* Flow<Boolean> */.data.map { if (it) listOf("selected") else listOf() })
    }

This approach allows reactive styling without extra mountpoints for the styling definitions.

The usage could be improved with convenience helpers like `hasClass("selected")` instead of `children("&.selected")` and examples could be added to the kitchensink.

This approach also enables using css transitions, which could be added to the styling dsl:

    box({
        css("transition: opacity 300ms;")
        children("&.hidden") {
            opacity { "0" }
        }
        children("&.visible") {
            opacity { "1" }
        }
    }){
        classList(/* Flow<Boolean> */.data.map { if (it) listOf("visible") else listOf("hidden") })
    }

**Comment by chausknecht** [comment]
Your are right, but I have already mentioned the ``className`` method earlier - which would be more fitting here:
```
val toggle = storeOf(true)
clickButton { text("toggle") }.map { !toggle.current } handledBy toggle.update

box({
    css("transition: opacity 300ms;")
    children("&.hidden") {
        opacity { "0" }
    }
    children("&.visible") {
        opacity { "1" }
    }
}){
    className(toggle.data.map { if (it) "visible" else "hidden" })
}
```
(no need for a list, if there is only one class to apply ;-) )

The use of ``children`` is rather some kind of workaround; the use of Kotlin variables should be preferred, as the *cascading* of CSS is an aspect, we do not foster to use. Instead we rely on the name of a class that could and will be shared between DOM elements.

Of course you can create the classes also via the ``style`` function - so we can omit the ``children`` directives:
```kotlin
val toggle = storeOf(true)
clickButton { text("toggle") }.map { !toggle.current } handledBy toggle.update

val hidden = style("hidden") { opacity { "0" } }
val visible = style("visible") { opacity { "1" } }

box({
    background { color { gray300 } }
    css("transition: opacity 300ms;")
}) {
    className(toggle.data.map { if (it) visible.name else hidden.name })
    +"Hallo Welt"
}
```

The key apsect does not change: This feels cumbersome!

I still would argue, that we need some better support within our DSL to enable dynamic styling without rerendering or relying on this pattern.
