### ISSUE TITLE
Move styling of inputField component into the theme

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#294]
In order to ease the custom styling within a custom theme, all of the basic styling ``basicInputStyles`` should be moved into the styling of ``inputField`` within our default theme.

Whoever fixes this bug should carefully inspect all other components and look for similar artifacts that should also be refactored.

This should not change the API of the component!

**Comment by mkempa-np** [comment]
The call of basicInputStyles in the method render() overrides the styling of the variant and size of the inputField. This shoud not happen. When moving the basic styling to the theme, the call of basicInputStyles should be erased from the render method.
