### ISSUE TITLE
Evaluate and establish an idiomatic Naming Convention for Filenames

### ISSUE THREAD

**Issue by ghost** [jwstegemann/fritz2#309]
We should evaluate which naming conventions for source filenames in Kotlin exist and apply those stricly within our project.
Without beeing specific for multiplatform projects, there is an official section within the style guide for Kotlin: https://kotlinlang.org/docs/coding-conventions.html#source-file-names

As we target different platforms, there might be good reasons to adapt another one or have different conventions for different source sets:
* PascalCase for ``jvmMain`` etc
* camelCase for the rest

But how to deal for *hybrid* sources like in ``commonMain``?

### Goal and Result
* All these decisions should be chosen carefully and based upon external opinions if somehow possible! 
* Also the decisions should be documented and linked, so that everybody can reason about in the future.
* It might be a good idea to *explictly* encourage fritz2 users to follow our scheme within their applications by adding appropriate sections to our (external) documentation.
* all our sources including demo projects should adapt these conventions

**Comment by Lysander** [comment]
As time goes by the Kotlin coding conventions got stricter an now there is the convention for `PascalCase`Names: https://kotlinlang.org/docs/coding-conventions.html#source-file-names

So we should follow this guideline!

**Comment by Lysander** [comment]
Closed in favor of #860!
