### ISSUE TITLE
Separate the component specification from the component implementations

### ISSUE THREAD

**Issue by hpehl** [jwstegemann/fritz2#314]
While searching for a suitable class hierarchy for my components in [patternfly-fritz2](https://github.com/patternfly-kotlin/patternfly-fritz2), I came across the classes, interfaces, mixins and functions defined in [`components.kt`](https://github.com/jwstegemann/fritz2/blob/master/components/src/jsMain/kotlin/dev/fritz2/components/components.kt). 

These definitions are very well done and most of them would perfectly fit also as the base for my components. Would it be possible to factor them out into its own module? That way I could add a dependency on it w/o depending on the actual fritz2 component implementations. 

I'd like to ask for moving everything but the following elements into an own module:

- `dev.fritz2.components.CloseButtonProperty`
- `dev.fritz2.components.CloseButtonMixin`

WDYT?

**Comment by chausknecht** [comment]
Thx for appreciating our approach!

Your proposal sounds quite reasonable and is definitly something we should consider. It might even be possible from my pov to integrate those abstractions directly into the core, if we could define a sharp separation between real common abstractions and rather implementation specific stuff (You already mentioned some of the latter)

This way some external client can continue only depending on the core.

BTW: Have you had already a look at ``managed.kt``? We just added / reworked some stuff (PR #310) for the [v0.9.1](https://github.com/jwstegemann/fritz2/releases/tag/v0.9.1) release that falls into the same category of definitions. Might be interesting for you as well :-)

Do you have already some feedback for improving / extending those APIs?
If we really want to expose those APIs, they should be in a quite stable state as we really want to reduce breaking changes towards our goal to reach a 1.0 version some day...

**Comment by hpehl** [comment]
Moving the component definitions into core makes sense to me. Currently there's a dependency to the styling module. Not sure how to deal with that.

What I like about the current design:

- common base interfaces like `Component<T>`
- abstractions and mixins like `ComponentProperty<T>` and `ElementMixin<T>`
- same behavior in and API for all components

What I don't like so much is that it can lead to ambiguity:

```kotlin
render {
    inputField {
        changes handledBy ...
        placeholder("foo")
        element {
            placeholder("bar")
            changes handledBy ...
        }
        events {
            changes handledBy ...
        }
    }
}
```

My vision would be that the component definitions are in core w/o a dependency to styling. But that would require a refactoring of the current code.

**Comment by chausknecht** [comment]
> What I don't like so much is that it can lead to ambiguity:

Interesting that we stumbled exactly (several times) upon this fact. Sadly we haven't found a nice solution and finally agreed upon the current approach to expose the underlying HTML tag to bypass a doubling of all HTML element interfaces.

If we evaluate to integrate the pure component API into the core, we should think again about this problem, as there might be a chance to find a better solution without abmbiguous declaration blocks!

Regarding the dependency of styling we could also investigate, whether there is a chance to integrate the basic interfaces into the core as for the components. On the other hand would this not satisfy your interest, as our ``render`` method signatures rely on our styling DSL... currently I have no clue how to separate this from the rest.

**Comment by hpehl** [comment]
At the moment I don't have a good answer to this issue either. Maybe I'll come up with a solution as I continue to work on my PatternFly components. If so I'll comment here...

**Comment by jamowei** [comment]
In my opinion there is a possibility to integrate our styling approach into our core later after we stabilized it enough. Then we are able to move the basic interfaces on which our components rely on to the core either. But for now I think it is to early to do that move and we should keep focus on stabilizing our products. Anyway it is good to have this issue and to keep this idea in mind!
And maybe we can find a way in between this two scenarios we can achieve earlier.

**Comment by chausknecht** [comment]
With the release of fritz2-RC1 we have introduced a new approach for building UIs with the [headless components](https://www.fritz2.dev/headless/) pattern. I consider this new approach as a *solution* for the issue, as it even goes one step further: It removes the whole need of some sort of specification at all. It does simply offer some components (build by an initial factory and bricks) that offer encapsulated  functionality, but does not force a user to any shape; neither within the code nor within the HTML representation in order to apply those.

I therefore close this issue.
