### ISSUE TITLE
Extend new ColorScheme approach

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#315]
With 0.9.1 we introduced a `ColorScheme` class which contains 4 colors (base, baseContrast, highlight, highlightContrast).
For now only our main colors (primary, secondary, tertiary) are using it. But we need to extend it also for our other colors (info, warning, danger,...) too. Also we should introduce functions in the components to set a `ColorScheme` e.g. for a `button`.
Therefore we need to cleanup our default theme for the components.

**Comment by WestHuus** [comment]
I've changed signal and neutral  colors to the `ColorScheme` 
![image](https://user-images.githubusercontent.com/60283586/115881026-9e48b680-a44b-11eb-9fb7-0926e9f516f4.png)

The `button` and `alert` component got a rework and works now with properties based on the `colorScheme`
