### ISSUE TITLE
Improve documentation of the gradle build file

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#325]
We should try to improve our documentation concerning the gradle build file entries:
- don't only show the final one, make a step by step explanation on the required features
- what does the plugin do
- check out [ktor docu](https://ktor.io/docs/gradle.html) for inspiration on this topic

Check out [Nick Apperly's post](https://kotlinlang.slack.com/archives/C01CSNG1HJ4/p1616365505023600) for understanding the motivation better!

**Comment by jwstegemann** [comment]
not that relevant anymore
