### ISSUE TITLE
Add convenience function to support color quadruples within styling DSL

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#326]
### Motivation

Our new approach for color management introduced by version [v0.9.1](https://github.com/jwstegemann/fritz2/releases/tag/v0.9.1) relies on quadruples of colors. Within each quadruple there are pairs of colors that have a high contrast (at least this is the **semantic** behind it) and therefore are prefered as combination to background and foreground colors.

Currently you often have to type the following repetitive pattern:
```kotlin
box({
    background { color { primary.base } } // set the background color
    color { primary.baseContrast } // set the foreground color with contrasted color of the chosen ColoorScheme
}) {
// come content
}
```
This pattern is so common, that we should consider to introduce a shortcut for that!

### Proposal
```kotlin
// within styling context:
coloring(primary) { base } // -> bg color is ``primary.base``, text color is ``primary.baseContrast``

// as the above should be the default case, it could be shortend further:
coloring(primary) // no bg color given -> choose ``base``!

// Invert the above
coloring(primary) { baseContrast } // bg color is ``primary.baseContrast``, text color is ``primary.base``
```
We must pass a ``ColorScheme`` object in order to implement the logic. So i don't see any other way than passing two objects.

The preliminary example would be shortend to:
```kotlin
box({
    coloring(primary)
}) {
// come content
}
```
### Thoughts

- I have some concerns with the syntax. Afaik we do not have a similar syntax right now (passing a parameter directly into a styling function). So probably we must strive for a solution that manages all the parameters inside the initial context function ``coloring``? (Drawback would be, that we must add anonther nesting like ``coloring { quad { primary } color { base } }`` which reduces the shortening effect)
- We must choose, whether the background or foregroundcolor is the *leading* color parameter! What is easier for the user? It might make sense to *invert* my approach and make the text / foreground color the leading one.

**Comment by jamowei** [comment]
In my opinion we should add this proposal to a recipe section in our docs instead and describe there how to create those helper functions for using in the styling DSL.
