### ISSUE TITLE
Concept a mechanism for connecting multiple stores 

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#34]
Concept a general way how multiple stores can interact with each other.

**Comment by jwstegemann** [comment]
Will be implemented by a dedicated `Handler`-class that offers a flow, which can be connected to a handler of another `Store` (by @jamowei)

**Comment by jwstegemann** [comment]
Implemented an `EmittingHandler` that can be connected to `Handler`s in other `Store`s as usual.
