### ISSUE TITLE
Optimize media breakpoints

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#342]
Check and improve the current media breakpoints which fritz2 components are using.

**Comment by WestHuus** [comment]
I found during checking up the media breakpoints some small bugs. 
I fixed and creates a PR 

**alignment.kt**

- fix typo in example codes

**background.kt**

- inserted the target for color of background responsive code

**border.kt**

- set the correct target for style function in BorderContext

**params.kt**

- removes default of target from property functions

**Comment by WestHuus** [comment]
Actually we use the default media breakpoints and I think it works correctly
