### ISSUE TITLE
Move Theme.fontColor and Theme.backgroundColor into the Colors interface

### ISSUE THREAD

**Issue by gsteckman** [jwstegemann/fritz2#347]
**Is your feature request related to a problem? Please describe.**

The Theme interface has a "val colors: Colors" but additionally two separate values for fontColor and backgroundColor. Moving the standalone fontColor and backgroundColor properties into the Colors interface would improve consistency by having all color definitions within the Colors interface.

**Describe the solution you'd like**

Move backgroundColor and fontColor from the Theme interface to the Colors interface.

**Describe alternatives you've considered**

When using a function to set a color, for example, BorderContext.color, the Receiver is Colors, so fontColor and backgroundColor cannot be accessed via Receiver but rather a call to Theme().fontcolor (or backgroundColor) can be used.

**Comment by jamowei** [comment]
Hi, good point we will fix that in v0.10.
