### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by jtdev** [jwstegemann/fritz2#348]
I have a simple question about Fritz2, but I cannot find a place to ask it.
The Slack channel is only available if you have an @jetbrains email address. And GitHub Issues isn't meant to ask questions, only for bugs and features. But GitHub has a feature called GitHub Discussions, that allows people to ask questions:
https://docs.github.com/en/discussions

> GitHub Discussions is a collaborative communication forum for the community around an open source project. Community members can ask and answer questions, share updates, have open-ended conversations, and follow along on decisions affecting the community's way of working.

It can be enabled via the "Settings" tab of this repo.

If you don't enable it, then what would be a good place for me to ask a question about Fritz2?

**Comment by jamowei** [comment]
Hi, did you try this link? https://surveys.jetbrains.com/s3/kotlin-slack-sign-up
Normally you get invited to the official Kotlin Slack quite fast and you can use your own e-mail address of course.
There you can join our official fritz2 Slack channel. At the moment this is our central place for questions like yours. ;-)

Sadly it is not easy to find the correct link...
![Screenshot_20210421_145334](https://user-images.githubusercontent.com/29158537/115556875-70c80580-a2b1-11eb-87ea-3b389ac715fc.png)

**Comment by chausknecht** [comment]
Thx for giving the advice for Github Discussions. TIL that this exist (still beta though).

This might be a nice solution and I promise we will evaluate this internally. Perhaps we will give it a try in the future.

The main problem for us is the fact, that our core team is not that big as other projects might be. So it is a bit cumbersome combined with more time for us to have multiple places where we should / must actively support our users (There is also StacKOverflow, which we sadly ignore most of the time). That is why I would support Jan's proposal to register yourself via Slack for the moment. (The UX for finding the link is really bad :-D)

**Comment by jtdev** [comment]
I got a Slack account now :)
It took about 6 hours after registration, to get it verified.
I see that a number of other Kotlin projects are using Slack as well.
