### ISSUE TITLE
Apply google's best practises for search engine optimization (SEO)

### ISSUE THREAD

**Issue by ghost** [jwstegemann/fritz2#354]
In order to improve the indexing for search engines of a SPA (which is **the** use case for fritz2!), google proposes some interesting and probably quite easy to accomplish tasks:
https://codelabs.developers.google.com/codelabs/making-a-single-page-app-search-friendly#0

We should try to apply those patterns as good as we can; or at least enable or support the app developer by doing so!

**Comment by Lysander** [comment]
This has no priority right now. Until somone provide some external PR, I close this one.
