### ISSUE TITLE
Add more typealiases for styling functions

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#367]
Current we have the following generic typealias:
```kotlin
typealias Style<T> = T.() -> Unit
```
But in most cases we need to use the `Style<BoxParams>` alias. Therefore we should consider to rename this default one to `Style` instead an more specific one to `StyleFlexBox` etc.
```kotlin
typealias Style = BoxParams.() -> Unit
typealias StyleFlex = FlexParams.() -> Unit
typealias StyleGrid = GridParams.() -> Unit
typealias StyleBasic = BasicParams.() -> Unit
```
Also it makes sense to introduce new typealiases for styling functions with parameters like this:
```kotlin
typealias Style1<A> = BoxParams.(A) -> Unit
typealias Style2<A, B> = BoxParams.(A, B) -> Unit
typealias Style3<A, B, C> = BoxParams.(A, B, C) -> Unit
// same for flex, grid and basic
```

**Comment by chausknecht** [comment]
Refer to issue #498 before working on this.
