### ISSUE TITLE
Components should return `Tag`s instead of `Unit`

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#378]
Most of the fritz2 components are returning nothing instead of the default fritz2 HTML elements which are returning `Tag`. That is why it is currently not possible to access the `domNode` of the component. But this could be needed when using them in external libraries.

For the majority of the components we need to change the first line `context.apply {}` to `return with(context) {} `. Then the underlying `Tag` is given back.

**Comment by chausknecht** [comment]
The proposed solution is not good enough to support [interaction based](https://docs.fritz2.dev/ComponentLibrary.html#composition-on-steroids) composition:
```kotlin
// works
clickButton { }.handler handledBy someHandler {
}

// but this is clumsy:
val button = clickButton { }
button.handler.map { button.tag } handledBy someHandler 
```
If a handler need to refer to the created tag, the simple combination proposed as `Combined` class is not sufficient! To achieve a fluent composition, the tag must be wrapped also inside of the event! Also the naming is not sufficient, as the `clickButton` does not return a handler, but an event!

**Comment by jamowei** [comment]
We have decided:
* every fritz2 component has to return a `Tag` which should be the most reasonable element of a complex component (compatibility with core + works in `renderEach`)
* components which are simple wrappers of native html elements provide `element` and `events` context as describe in EfC 411/415
* components which are currently returning a `DomListener`  instead of a `Tag` (for calling the `handledBy` function directly) will getting an appropriate convenience function to minimize the migration overhead. Therefore we introduce new `handledBy` extension function for special `Tag`s, like `Tag<HTMLButtonElement>`.
* rename `pushButton` to `clickButton` to minimize the migration overhead because `clickButton` is used most of the time
* for consistency in our global-managed components (`modal`, `toast`,...) all factory-functions don't need a `RenderContext` as receiver in contrast to the other components. Therefore they can be called everywhere (like `window.alert`).
* for easier handling events without needing a `Store` (no state change) there is a new `handledBy` function for creating an "ad-hoc"-handler.
```kotlin
clickButton {
    //...
} handledBy {
    toast { 
        //...
    }
}
```
