### ISSUE TITLE
Add Slider component

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#386]
The should consider a Slider component, like [this one](https://chakra-ui.com/docs/form/slider).

Focus should be the ability to:
- define steps (by function and also maybe by discrete set)
- choose icon for sliding bubble

**Comment by jamowei** [comment]
I would prefer `range` instead of `slider` as name for the component because it is the same like `<input type="range"/>`.

**Comment by chausknecht** [comment]
There exist different names for the same thing, even the Mozialla docs use the term _slider_ within their [explanations](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) to the ``input type="range"``:
* Qt: [QSlider](https://doc.qt.io/qt-5/qslider.html#details)
* WinForms: [TrackBar](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/controls/trackbar-control-windows-forms?view=netframeworkdesktop-4.8)
* WPF: [Slider](https://docs.microsoft.com/de-de/dotnet/api/system.windows.controls.slider?view=net-5.0)
* Gtk: [GtkScale](https://developer.gnome.org/gtk3/stable/GtkScale.html)
* Material-UI: [Slider](https://material-ui.com/components/slider/)
* Bootstrap: [Range](https://getbootstrap.com/docs/5.0/forms/range/)
* Chakra: [Slider](https://chakra-ui.com/docs/form/slider)

I have not a clear opinion towards the name - luckily chaning this during development should not be that hard!
