### ISSUE TITLE
Fix `ToastComponent` styling issues

### ISSUE THREAD

**Issue by haukesomm** [jwstegemann/fritz2#388]
Currently there are some styling issues regarding toasts:
- ~~The toast's close button is rendered _next_ to the toast's content which makes it impossible to render custom contents immersively (e.g. alerts which should fill the whole canvas of the toast). The close button should be changed to render on top of the toast's content to address this issue. Find a screenshot below that demonstrates the issue:~~  
This has already been addressed with #471 
![Bildschirmfoto 2021-05-17 um 17 38 21](https://user-images.githubusercontent.com/12587543/118516841-fa46e800-b736-11eb-9a1b-ad157bcaac6b.png)

- On mobile devices, depending on their placement, toasts may partially be rendered outside of the viewport. To address this, dedicated mobile styles should be implemented.

Additionally, some of the improvements suggested in #396 should be implemented as well:
- Move styles to the theme 
- Use proper z-indices

**Comment by chausknecht** [comment]
Rendering on top won't solve the issue imho, because toasts are meant to be stacked - it would be quite irritating to have some close button between two toasts...

The main problem seems to me, that there is currently no way for the toast to _know_, which colors are used by the content.

So there are some approaches for this:
- don't render the closeButton automatically, but enable this in an easy way inside the content (there must be a solution for the ``alert`` then!) modals provide this mechanism already optionally.
- find a better way to render a fitting container around the content like this works right now. 
- make the coloring information available for the surrounding toast component for each toast, in oder to apply this to the closeButton and the container around the content.

**Comment by haukesomm** [comment]
> Rendering on top won't solve the issue imho, because toasts are meant to be stacked - it would be quite irritating to have some close button between two toasts...

In order to address the confusion: Actually my suggestion was to render the close button on top of the the other content of the toast, in the top layer so to speak. This way the alert could take up full width of the available space, regardless of the close button. I did _not_ mean to render it above the toast in a way that it appears outside of the toast.

Your solutions look promising as well, though. I will definitely consider them, thanks for the input!

**Comment by haukesomm** [comment]
To give a short conclusion real quick:

- `ToastComponent` implements the `CloseButtonProperties` interface and with it the `CloseButtonStyle` property.
The close button's color scheme can be set to match the content's color scheme this way.

- The problem with the background of the close button not matching the color scheme can be solved by rendering it above the content (via absolute positioning, think of it as an extra layer). Some right padding might dynamically be added to the content so it does not get covered by the close button, yet still draws it's background behind it.

- Optionally it is also debatable whether the toast itself needs a styled container or if all styling should be done by the component passed in via the `content` property.

The code snippet below shows how an alert-toast can be created right now. In the special case of toasts with alert's as their content a convenience factory might be a good thing to include as it can be quite cumbersome to write.

```kotlin
showToast {
  val severity: AlertSeverity = Theme().alert.severities.info

  placement { bottomRight }

  // Apply the alert's color scheme to the close-button:
  closeButtonStyle {
      color { severity.colorScheme.main }
  }

  content {
      alert {
          severity { severity }
          variant { leftAccent } // <-- only for demonstration purposes
          stacking { compact }
          content("Menu item clicked")
      }
  }
}
```

The result looks like this:
![Bildschirmfoto 2021-05-25 um 17 40 31](https://user-images.githubusercontent.com/12587543/119527231-6d2c1080-bd80-11eb-8484-543d7d1bca50.png)
