### ISSUE TITLE
Make `Icons` definitions interface in extendable for custom icon definitions

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#397]
Currently there is no good approach to add custom icons to the `Icons` definition interface in fritz2 styling. Therefore you need to set the icons manually in icons context and can't use the DSL instead. Of course you can extend the `Icons` interface with your own but they are then only accessable via `Theme().icons`.
```kotlin
// in components
val icon = ComponentProperty<(Icons.() -> IconDefinition)?>(value = null)
```

**Comment by metin-kale-cf** [comment]
Possible working approach: 

CustomIcons.kt:

    private val Icons.FALLBACK get() = warning

    interface CustomIcons : Icons {
        val customIcon: IconDefinition
    }

    val Icons.customIcon get() = (this as? CustomIcons)?.customIcon ?: FALLBACK



Custom Theme:

    override val icons: CustomIcons = object : CustomIcons, Icons by super.icons {
        override val customIcon: IconDefinition = IconDefinition(...)
    }

**Comment by metin-kale-cf** [comment]
above solution was working in v0.9.2, but it does not work in v0.10. 

Line

https://github.com/jwstegemann/fritz2/blob/a5611f59a0c86a05fa1e3b57d440fca49cfc6247/styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt#L416

should be 

    override val icons : Icons = MonoIcons()

to allow working with interfaces again
