### ISSUE TITLE
Fix centering of `modal`

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#399]
Possible styling solution:
```kotlin
override val centered: Style<BasicParams> = {
    position {
        fixed {
            top { "50%" }
            left { "50%" }
        }
    }
    css("transform: translateX(-50%) translateY(-50%);")
}
```

**Comment by chausknecht** [comment]
We have some trouble regarding the bigger picture here and include issue #400 into our thoughts:

To enable scrolling outside of the modal and to center a modal also vertically does not match! Those properties are mutual exclusive. This fact makes it harder in any way to provide:
- a nice decalartive approach (which property wins if user provide both?)
- a customizable theming, as its implementation must probably use cases...

The key questions are therefore:
- can we arrive with a nice DSL that describes the rendered modal in an understandable way?
- can we disentangle those mutual exclusive properties by DSL or probably component factory? (different components for those different use cases?)

On top we must consider to offer some kind of ``verticalStreched(true)`` property, to enable kinda full screen modal. Very useful for some kind of step based content, where each step has different content size. This would lead to _vertical flickering_ otherwises.

Here is a (bad) summary of all those aspects as DSL, where the ``sizes`` property is as available right now:
```kotlin
modal {  
    size { normal } // small, large, full:
    // full spezial: -> whole Screen without margins
    size { auto } // would make sense in horizontal aspect -> no wrapping!

    // Corelation: verticalCentered always``false``
    outerScrolling(true)

    // Corelation: outerScrolling always``false``
    verticalCentered(true)

    // Corelations: 
    // - outerScrolling always``false``
    // - verticalCentered always``false``
    stretchVertical(true)

    // stretch { horizontal / vertical / both } makes no sense, as ``size { large }`` represents exactly this!
}
```

### Example for flexible centering independently for both directions:

(Uses old ``zIndex`` API and not PR #415 yet!)

```kotlin
flexBox({
    zIndex { modal(0) }
    position {
        fixed {
            left { "0px" }
            top { "0px" }
        }
    }
    width { "100vw" }
    height { "100vh" }
    //overflow { auto }
    background { color { gray700 } }
}) {
    div({
        background { color { gray100 } }
        zIndex { modal(1) }
        css("--main-level:1rem")
        // horizontal
        css("--modal-max-width:50vw")
        maxWidth { "var(--modal-max-width)" }
        width { "100%" }
        // vertical
        css("--modal-max-height:50vh")
        maxHeight { "var(--modal-max-height)" }
        height { "100%" }

        overflow { auto }

        position {
            fixed {
                top { "max(calc(50% - var(--modal-max-height) / 2), var(--main-level))" }
                left { "max(calc(50% - var(--modal-max-width) / 2), var(--main-level))" }
            }
        }
        // zentriert
        css("transform: translateY(calc(-1 * max(calc(50% - var(--modal-max-height) / 2), var(--main-level))))")
        css("transform: translateX(calc(-1 * max(calc(50% - var(--modal-max-width) / 2), var(--main-level))))")
    }) {
        + "some content... could be extremely large!"
    }
}
```

**Comment by chausknecht** [comment]
Ok, here is a new, far better example that also copes with scrolling (issue #400): [Code](https://gist.github.com/chausknecht/1e1b9d8955900633419c1293ceaa8cba)

This is mainly inspired by [chakra-ui](https://chakra-ui.com/docs/overlay/modal)'s solution:
- always a pair of tow ``div``s
- parent is a ``flexBox`` that copes with 
  - alignment (and horizontal placement if this is really needed -> ``justify-content``)
  - scrolling: ``overflow: auto``
- child is the real modal, sizing via ``max-width``

DOM schema for final implementation should be like this:
```kotlin
central modal div/
├─ overlay div
├─ first modal flexBox/
│  ├─ content div
├─ second modal flexBox/
│  ├─ content div
```

This would enable a DSL as follows:
```kotlin
modal {
    // One should also be able to provide normal sizes like "90%", "880px" and so on
    // full -> no margins!
    // large -> 100vw with margins!
    // small / normal -> some ``vw``-value
    size { small / normal / large / full }

    // -> ``align-items``: flex-start, ...
    // Problem: only ``start`` works well with larger content than screen-height!
    placement { start / center / end / stretched } 

    // provide styling parameter
    content({
        // styling -> applies to inner Div, not to ``flexBox`` wrapper
        // User *is able* to set ``overflow: auto`` if desired
    }) {
        // content
        // right place to define ``overflow: auto`` for complex inner design
        // (think of fix header, real content and fixed footer)
    }
}
```
