### ISSUE TITLE
AppFrame: Accordion Navigation Menu

### ISSUE THREAD

**Issue by EvaBS** [jwstegemann/fritz2#402]
For a big project at work, we need an accordion menu inside the left side navigation area of the app frame.

I would like to propose the following enhancements for the appFrame:

- navSection is clickable and opens the corresponding section (displaying the contained navLinks)
- provide option to keep only one section open at a time (auto-close all other sections on clicking a navSection)
- navSection header and navLink entry can be styled for "opened"/"closed" plus "active"/"inactive" 
--- when auto-close is on, opened is always active and closed is always inactive).
- menu publishes its current state (which section and link are active, for example)

This could be implemented as a standalone navMenu component which can also be used inside the nav {} area of the app frame.

**Comment by chausknecht** [comment]
We should investigate if those feature requests probably apply to the new separate ``menu`` component (PR #362) and could be realized therein as ``appFrame`` is supposed to use the new ``menu`` component anyways.

If (some) of those proposals will not get accepted we should consier to show a way, how to achieve this by hand using the customization capabilities of the ``menu`` component at least! This sounds like an interesting use case anyways, so at minimum a good example for deep customizations!
