### ISSUE TITLE
Investigation of some DataTable problems

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#404]
We should investigate the following unexpected and annoying behaviours:
- how to realize a smooth editable table without _flickering_ as the whole row gets deleted and newly rendered even if the ID does not change, but only the content of *one* cell!
- how to preserve the _tab order_ for an editable cell.
- try to find ``Flow`` that reduces the speed since the finalization of the table. Probably this is related with too aggressive reaction to changes. Some cache / surpressing of unchanged data could be helpful there.

**Comment by metin-kale-cf** [comment]
#411 solves this issue

**Comment by chausknecht** [comment]
Unfortunately PR #411 does not work! We have to consider that a possible activated sorting will change the index, which must be reflected by renderEach.

I have tried to combine both approaches as follows:

val indexedRowIdProvider: (IndexedValue<T>) -> Int = { (index, value) -> 
    rowIdProvider(value).hashCode() * 31 + index.hashCode() 
}

Unfortunately this also has improved the situation of the editable DataTable examples within the KitchenSink only partly!

In fact it is possible that we must delegate more responsability on top of the client for providing an efficient yet sufficient rowIdProvider, which reflects the need of the table:

    often the id of the model is sufficient
    if all / many columns are editable, their property counterparts need probably to be included also

We must investigate those concerns and find a solution and also probably some recipes for the users.

**Comment by chausknecht** [comment]
The core of this problem and also the "flickering" when sorting the table is with high probability located in the outer ``renderEach`` call of the content rendering method: We absolutly must remove the index (and other changing properties) from the id providing. Only the ID should really be responsible for identifying the ``<tr>`` element, so it can be just _moved_!

The sorting order should be simply applied by the appearence of the rows within the flow given into ``renderEach`` (which is sorted before).

In order to provide the current _index_ to each cell, we must combine the index with the row content in the inner ``renderEach``-Block! That means there is the need to store the ``id -> index`` relation within a separate store or as extension of the datamodel. This way the index can be provided to each cell and be used for styling purposes for example.

**Comment by Pitel** [comment]
Maybe the flickering has simple solution: [debounce](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html) with short (50 ms?) timeout.

**Comment by chausknecht** [comment]
> Maybe the flickering has simple solution: debounce with short (50 ms?) timeout.

I do not think so, as the internal node matching still would affect *all* rows and not just the one that has changed. So this would probably only delay the problem a bit. I have already tried to apply my own proposal, but that is more work than first expected. 

Hopefully I can work on this bug very soon!
