### ISSUE TITLE
Unclear error handling

### ISSUE THREAD

**Issue by Pitel** [jwstegemann/fritz2#425]
**Is your feature request related to a problem? Please describe.**
I'm learning Fritz2, and I'm making a login form. When user enters bad credentials, and the API returns HTTP 401, I'd like to show the error (toast). I can't find a way how.

Another related issue is in `Tracker`. When I start the remote request, and it fails, the button keeps spinning and I couldn't find any method how to stop it.

**Describe the solution you'd like**
* Make special chapter in documentation about error handling.
* Demonstrate it in remotes example.
  * I have uBlock, which blocks the request to the domain you use in this example. I see the error in developer console, but nothing in the UI.

Abouty the tyracker problem, I'd suggest to change the `track` method like this:
```kotlin
// OLD (0.10.1)
return operation().also { state.value = null } 

// NEW
return try { operation() } finally { state.value = null }
```

**Describe alternatives you've considered**
I couldn't find any. Just provide some documentation and example.

**Additional context**
My handler looks like this. If you could show me how to display the error toast, I'd be grateful.

```kotlin
val login = handle { model ->
    loading.track {
        if (validator.isValid(model, Unit)) {
            try {
                http("/apiIs2/authUser")
                    .acceptJson()
                    .contentType("application/json")
                    .body(
                        JSON.stringify(
                            json(
                                "username" to model.login, "password" to model.password
                            )
                        )
                    )
                    .post()
                    .getBody()
                router.navTo("main")
            } catch (t: Throwable) {
                console.log(t)
                toast { // NOT DISPLAYED :(
                    content {
                        alert {
                            title("Login error")
                            content(
                                if (t is FetchException && t.statusCode == 401.toShort()) {
                                    "Bad credentials"
                                } else {
                                    "$t"
                                }
                            )
                        }
                    }
                }
            }
        }
        model
    }
}
```

**Comment by Pitel** [comment]
Fix for the toast problem: replace `toast {}` with `showToast {}`.

**Comment by chausknecht** [comment]
> Another related issue is in Tracker. When I start the remote request, and it fails, the button keeps spinning and I couldn't find any method how to stop it.

Can you show the relevant code, how you activate the spinner on a button?

This should resemble this snippet from the [KitchenSink](https://components.fritz2.dev/#Button) demo:
```kotlin
clickButton {
    text("Play")
    loading(loading.data) // not shure if your tracker is globally accaisble; probably its backed within a store as proposed by the documentation (https://docs.fritz2.dev/Tracking.html)
} handledBy someHandlerOfYours
```
``loading`` property of ``PushButtonComponent`` need some ``Flow<Boolean>``, which the tracker offers. So I do not see any reason right now, the spinner should keep moving after the request is finished...

**Comment by Pitel** [comment]
My use looks exactly the same as the demo you mentioned.

There is your test case, the loading keeps spinning:
```kotlin
import dev.fritz2.binding.RootStore
import dev.fritz2.components.clickButton
import dev.fritz2.dom.html.RenderContext
import dev.fritz2.tracking.tracker
import kotlinx.coroutines.delay

fun RenderContext.loadingTest() {

    val fooStore = object : RootStore<Int>(0) {
        val t = tracker()

        val h = handle {
            t.track {
                delay(500)
                throw Exception("Boom!")
            }
        }
    }

    clickButton {
        loading(fooStore.t.data)
    } handledBy fooStore.h
}
```

**Comment by EvaBS** [comment]
I display my errors like this:

```
// my serverErrorStore is of type <MyMessage?>, you could use ComponentValidationMessage or whatever else fits your usecase

// in RenderContext, render all server messages in the same place in app. 
// you could also make this store a list for multiple messages 
serverErrorStore.render { message ->
    if (message != null) {
        showToast {
            content {
                alert { content( //... message content) }
            }
        }
    }
}

// in REST-Handler in Store when error occurs:
serverErrorStore.update(thisErrorMessageWhichOccurredJustNow)

// clear store when you're done with the error, I do that when I enter a handler or new page content is rendered
serverErrorStore.update(null)

**Comment by chausknecht** [comment]
The problem is that you do not catch the exception within the call of ``track``! The track function internally does not cope with exception handling:
```kotlin
    suspend fun <T> track(transaction: String = defaultTransaction, operation: suspend () -> T): T {
        state.value = transaction
        return operation().also { state.value = null } // the ``also`` will never be called 
                                                       // -> no no ``null`` inside state 
                                                       // -> so no change to ``false`` for ``t.data``!
                                                       // -> so the spinner keeps turning
    }
```
In fact I don't see any easy solution to this problem, as we have no alternative return value here! As we need to return a ``T``, there must be one. Only ``operation`` can give us one, but it would not, if it fails ;-)

So the solution is to manage the exception handling inside of your passed ``operation``:
```kotlin
val fooStore = object : RootStore<Int>(0) {
    val t = tracker()

    val h = handle {
        t.track {
            try {
                delay(500)
                throw Exception("Boom!")
                it + 1 // will be never reached
            } catch(ex: Exception) {
                it
            }
        }
    }
}

clickButton {
    text(fooStore.data.map { it.toString() })
    loading(fooStore.t.data)
} handledBy fooStore.h
```

I have to admit that this is none obvious and also [not documented](https://docs.fritz2.dev/Tracking.html) right now!

I think there is a need for a discussion, whether there is a way to improve this; so I will add a discussion marker :-)

**Comment by chausknecht** [comment]
Ok, I have to correct myself: Of course it is quite easy to make ``track`` safe for unsafe operations.

I already provided PR #430 to improve this situation!
