### ISSUE TITLE
Move areas from Popover into an own component and use `DropdownComponent` to create popovers

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#438]
In order to simplify things we should consider the following points about popovers and dropdowns:

- We should consider moving the below area structure from the `PopoverComponent` into an own component.
The new component could be embeddable within modals too.
- The new `DropdownComponent` could be used to render popovers in the future. 
- As it becomes a more versatile component, it might also be a good idea to find a better name for the `DropdownComponent` as described in #447 .

![grafik](https://user-images.githubusercontent.com/70946811/121534778-d444f880-ca01-11eb-9b68-a958f4f46845.png)

**Comment by chausknecht** [comment]
How about removing the old popover completly?

If I have grasped the differences correctly, there is only the _area_ functionality and the _marker_ which are not part of the current Dropdown. For the area we will consider a separate component, so the marker would be the only feature missing.

Depending on the implementation of the dropdown it might be a solution to add this optionally to this component, so one could easily realize the current popover by combining the dropdown with the new area component - like the dropdown menu combined by two independent components.

**Comment by jamowei** [comment]
We should also consider to remove the default `toggle` implementation, because it is confusing and not easy to define a practical default one.
Actual in `dropdown` component:
```kotlin
val toggle = ComponentProperty<RenderContext.() -> Unit> {
    pushButton {
        icon { menu }
        variant { ghost }
    }
}
```
