### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by Pitel** [jwstegemann/fritz2#444]
**Is your feature request related to a problem? Please describe.**
Fritz supports HTTP/REST, WebSockets, it would be nice to also support GraphQL.,

**Describe the solution you'd like**
`GraphQLEntityRepository`, `GraphQLQueryRepository`, DSL for writing queries.

**Describe alternatives you've considered**
Use Apollo JS client and write wrapper.

**Additional context**
I'm currently writing it. If my employer allows it, I'll submit MR. Is there something you'd also like to see in the MR to get it accepted?

I'm quite new to Fritz and GraphQL, so if there is someone who can mentor me and help me to implement it correctly, I'd be glad.

**Comment by jwstegemann** [comment]
This is definitely worth exploring. I had some ideas about GraphQL but never found the time to really start working on it. So I would be very happy to have a look at your ideas and provide help, wherever I can.

For public discussions we can use this issue and the fritz2-channel @ JetBrains' Slack. If you want to talk more privately, leave me a message at jwstegemann at gmail

**Comment by jwstegemann** [comment]
After we removed the repositories from fritz2 (see Release Note for 1.0-RC2) entirely, we will not add GraphQL-support anymore.
