### ISSUE TITLE
Find better name for `DropdownComponent`

### ISSUE THREAD

**Issue by haukesomm** [jwstegemann/fritz2#447]
As the `DropdownComponent` is used in more and more places and also can be opened in various positions around it‘s toggle we should consider finding a better name for the component.

**Comment by chausknecht** [comment]
Should be solved together with issue #438 

Also consider ``popup`` as common name? This is a nice generic name to unite both components. It just names the overall effect, without beeing too specific.

The current ``popover`` could also probably remain for some time as deprecated function; like ``dropdown`` too.

**Comment by WestHuus** [comment]
The actual name is `PopperComponent` . I create this `component` at time, for handle all other `components` which displays a content after triggering an event, like `tooltip` `popover` and `dropdownMenu`
