### ISSUE TITLE
Evaluate migrating to a better test framework

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#454]
As the development of fritz2 started, the infrastructure for multiplatform projects was rather poor, as it was bleeding edge and lots of alpha status.

Meanwhile the ecosystem has evolved and there might be better choices for writing automated tests than the built-in test framework. The latter is rather weak when it comes to:
- assertions (not expressive, no custom matchers, no grouping / multi assert)
- data driven tests
- property based testing is not supported at all
- output rather limited (in failure case)

We should investigate, which frameworks are popular in the Kotlin multiplatform world and then pick one and try to invest two days or so to get a feeling, how much work it will be to migrate all our tests.

## Frameworks (Please add):
- [kotest](https://kotest.io/)

**Comment by Pitel** [comment]
Kotest is currently unsuable with JS IR: https://github.com/kotest/kotest/issues/2163

**Comment by chausknecht** [comment]
Thx for this information.

Bad and sad news... 😢

**Comment by sksamuel** [comment]
Kotest 5.0 will support JS IR. It's already working in a feature branch and 5.0 will probably drop in around 4 weeks.

**Comment by chausknecht** [comment]
Good news 👍 
Thx for your efforts!

**Comment by jwstegemann** [comment]
Maybe in the future.
