### ISSUE TITLE
Improve API documentation of components

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#455]
Currently we have no consistent concept of API documentation for our components:

- sometimes the factory function offers the main KDoc and the corresponding component-class only offers minimal documentation.
- sometimes it is vice versa!
- sometimes *both* is true

This is not good!

## Considerations

- within an IDE the only the factory functions exist in UI code. So the user has direct access to their documentation. To follow a ``@see`` link, one click is needed.
- some components offer different factory methods but share a common (or base) component class. To avoid duplication of documentation it would be reasonable to put the documentation there.

## Proposal

- write a rather small documentation with a common usage example at the factory function in order to enable the user to get started (like the first usage section within the KitchenSink demos!). Add a ``@see`` targeting the corresponding component class
- write a full and exhaustive documentation with edge case examples and so on at the component class.

This should combine the advantages of both places with minimized disadvantage (duplication) od redundancy.

**Comment by TMWesley** [comment]
Hello, is this a REST API? If so I would be happy to help!

**Comment by chausknecht** [comment]
Hi :-)

No, this is about our internal API documentation using KDoc formatting language:
```kotlin
/**
 * Here we document about the `Element` class - tell the user what it is about, how to use it
 * and which are important parameters for the constructor and so on.
 *
 * We do this also for some methods or important vals
 */
class ElementComponent {
}

/**
 * This bug is about where to write which part of the example and usage related stuff. 
 * Here or above to the corresponding class ;-)
 */
fun RenderContext.element(...) {
}
```

So thx that you asked, but I believe this is only feasable, if one has rather deep knowledge of our components library obviously.

If you have special interest in fritz2 and you want to help, we might find a more feasable task for you?

**Comment by TMWesley** [comment]
Thank you for your kind reply. At the moment I am looking for a REST API, but may reach out in the future to help on other projects. Take care
