### ISSUE TITLE
Popover overlapped by AppFrame

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#460]
The z-indices for AppFrame is higher than a Popover, but the opposite would make more sense. I think a popover could have the highest z-index, because it is only showing when the toggle element is clicked.

![image](https://user-images.githubusercontent.com/84390402/123282641-fdd64780-d50a-11eb-9cfb-748673f1b77e.png)

**Comment by EvaBS** [comment]
Stumbled across the same thing today, I second Metins suggestion

**Comment by chausknecht** [comment]
Adapt `ZIndices` so that all overlays have higher values than `AppFrame` - not only `Popover`!

**Comment by haukesomm** [comment]
I don't think that adjusting z-indices to be higher than the `AppFrame` would work for all instances in which a dropdown is used.
While it would make sense in most cases, there are cases in which problems arise:
- Scrolling: A popover floating around a button might overlap the `AppFrame` with the toggle element still being below it: ![Bildschirmfoto 2021-07-19 um 11 23 10](https://user-images.githubusercontent.com/12587543/126136980-58af687e-8442-49e0-81c4-5aa999b19179.png)
- The same also applies for `dropdown`s and all other components floating around a toggle element

Imo it would be better to either
- Alter the z-index of the respective `popover` individually if you are sure it won't cause visual glitches (via the styling-dsl)
- Choose the placement of the `popover ` in a way that it does not overlap the `AppFrame`, e.g. place it to the right of the toggle if it would overlap with the navigation on the left. This might not always be possible, depending on the exact location of the popover

By using one of the above solutions no visual inconsistencies occur in the standard use-cases while still allowing alternative behavior when needed.

**Comment by haukesomm** [comment]
@WestHuus is working on a new component replacing `popover` in the long term that will avoid the aforementioned issues by  placing the popover automatically. Thus, I'll close this issue for now ✌🏻 
See #438 as well.
