### ISSUE TITLE
click() from JS ignores preventDefault

### ISSUE THREAD

**Issue by Pitel** [jwstegemann/fritz2#461]
**Describe the bug**
When I call `.click()` method on `clickButton` inside `form` directly from JS (either console, or test), the form gets submitted.

**To Reproduce**
```
form {
  clickButton(id = "button").preventDefault()
}
```
```
document.getElementById("button").click()
```
It submits the form and redirects. Effectively freezing Karma test.

**Expected behavior**
Nothing happens. (Or handler gets called, if there is any.)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 93

**Comment by chausknecht** [comment]
Have you checked the answer in our slack channel?
https://kotlinlang.slack.com/archives/C01CSNG1HJ4/p1624864560015300

Does this close the issue?

**Comment by Pitel** [comment]
Oh, right now I did.

To answer/comment on some of the points...

Yes, I have some `handleBy` after the `.preventDefault()`, but I just wanted to create minimal testabla snippet.

I've `delay(50)` rigth after render, before traversing the document. I quickly realized that unless I do that, the handler is not called and the test fails anyway.

I think it's semanticaly more correct to use `<form>`, becaus it is a login form. But as workaround, I'm now using `<div>` anyway to make it work.

I thought about preventing the submit event of the form just an hour ago, but I couldn't find a way with Fritz. Can you help me with this? Because this might be the solution I want.

**Comment by jamowei** [comment]
https://stackoverflow.com/questions/932653/how-to-prevent-buttons-from-submitting-forms/

This a not a problem within fritz2 itself. It is the standard mechanism in HTML for a `<form>` element. I wrote an example with two possible solutions to prevent the default behavior of a `<form>`. I would recommend to use a `<div>` instead when the default behavior of `<form>` element is not wanted.
```kotlin
    val store = storeOf("fritz2")

    render {
        form { // replace by div

            // 1. solution (html native)
            attr("onclick", "return false")

            // 2. solution (fritz2-way, but more expensive cause of flow-collection)
            clicks.preventDefault().events.watch()

            formControl {
                inputField(value = store)
            }

            clickButton {
                text("Save")
            } handledBy modal {
                content {
                    span { +"Saved!" }
                }
            }
        }
    }
```
I hope that helps.

**Comment by Pitel** [comment]
@jamowei The second solution doesnt work. Bot the first one does, so thanks for your help. :+1:
