### ISSUE TITLE
Issues closing popover on some devices/browsers, etc.

### ISSUE THREAD

**Issue by EvaBS** [jwstegemann/fritz2#464]
When clicking a popover's toggle when it is already opened, it does not close reliably.

Reproduce: See https://components.fritz2.dev/#Popover and then use any toggle to try and close the popover.

My guess is that it loses focus when the button is clicked, therefore hides itself and is then opened again by the button click.

**Comment by haukesomm** [comment]
Unfortunately I am unable to reproduce this on both the current versions of Chrome (91) and Firefox (89) on Windows 10 and macOS Big Sur. Do you have some more information on which browser/OS your are testing on?

**Comment by EvaBS** [comment]
Win10, latest versions of Chrome, Firefox and Opera. Using the toggle to close the popover works on neither buttons nor icons, I have tried all examples in the components demo.

**Comment by EvaBS** [comment]
Works fine on mobile, btw

**Comment by haukesomm** [comment]
> On iOS/Safari close on blur does not work at all, though...

We currently have an open issue for this, see #446 ✌🏻
