### ISSUE TITLE
Slider: update Store while dragging

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#466]
The Slider updates the store only after dragging has ended. When putting a text next to the Slider to show the value of the actual Slider, it will only be updated after the mouse have been released.  

When the user has to select a precise number, it will be difficult to catch that number, because there is no live update while dragging. 

![Animation](https://user-images.githubusercontent.com/84390402/123928211-ff31c500-d98d-11eb-904e-69824f384141.gif)

**Comment by chausknecht** [comment]
Please have a look at the "Deep Customization" section of the [KitchenSink](https://components.fritz2.dev/#Slider) demo page of the slider. Does this fit your needs?

In a first draft there was also the "currentPercent" event available, but we dropped this in favour of simplicity. If this is such important for you to have, we could probably reintegrate this event.

**Comment by chausknecht** [comment]
You can use the `currentValue` event from the slider:
```kotlin
val valueStore = storeOf(42)
val currentStore = storeOf(42)
slider(value = valueStore) {
    events {
        currentValue handledBy currentStore.update
    }
}
storeContentBox("Value") {
    valueStore.data.render { span { +it.toString() } }
}
storeContentBox("Current Value") {
    currentStore.data.render { span { +it.toString() } }
}
```

I think that is what you are looking for?

Plase close the bug then :-)

**Comment by metin-kale-cf** [comment]
the `currentValue` Event works fine, thank you 👍

**Comment by chausknecht** [comment]
> When the user has to select a **precise number**, it will be difficult to catch that number, because there is no live update while dragging.

Please have in mind, that this control might be the wrong UI element for this kind of task! It should rather be used for data that only need some approximate value.
