### ISSUE TITLE
WebComponent demo is broken

### ISSUE THREAD

**Issue by Pitel** [jwstegemann/fritz2#467]
**Describe the bug**
https://examples.fritz2.dev/webcomponent/build/distributions/index.html is broken, the city attribnute is not displayed. Error in console is displayed instead.

**To Reproduce**
1. Go to https://examples.fritz2.dev/webcomponent/build/distributions/index.html
2. The city is not displated, but it should be according to code
3. Open console
4. There is an error: Uncaught TypeError: this.webComponent.attributeChangedCallback is not a function
5. When you try to chage the city attribute, the error is repeated.

**Expected behavior**
City is displayed and can be changed.

**Screenshots**
![Snímek z 2021-06-30 12-14-53](https://user-images.githubusercontent.com/113248/123943980-f3013400-d99c-11eb-8943-a29fd54810e7.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome and Firefox
 - Version 91 and 89

**Comment by chausknecht** [comment]
This might be a duplicate / enhancement of issue #83
