### ISSUE TITLE
Trying to listen to websocket connection in Kotlin/JS React

### ISSUE THREAD

**Issue by Toumani** [jwstegemann/fritz2#491]
I'm developing a chat app with Kotlin/JS React in KMM. When I use websocket ([as explained in the doc](https://docs.fritz2.dev/Websockets.html)) I have "Uncaught TypeError: this$.trySend_11rb$ is not a function" in my browser console whenever I receive a message from server. This seems to be caused in watch() function. Here's my code :

**Client**

    val session = websocket("ws://${window.location.host}/ws/send").connect()

    class Tchat : RComponent<TchatProps, TchatState>() {
    
        override fun componentDidMount() {
            session.messages.body.onEach {
                console.log("Received $it")
            }.watch() // watch is needed because the message is not bound to html
       }

        override fun RBuilder.render() {
            // renders chat layout
        }
    }

**Server (Ktor)**

    fun main() {
	val connections = Collections.synchronizedSet<Connection>(LinkedHashSet())
	val messages = mutableListOf<Message>()
	val port = System.getenv("PORT")?.toInt() ?: 9090

	embeddedServer(Netty, port) {
		install(ContentNegotiation) {
			json()
		}
		install(CORS) {
			method(HttpMethod.Get)
			method(HttpMethod.Post)
			method(HttpMethod.Delete)
			anyHost()
		}
		install(Compression) {
			gzip()
		}
		install(WebSockets) {
			pingPeriod = Duration.ofSeconds(15)
			timeout = Duration.ofSeconds(15)
			maxFrameSize = Long.MAX_VALUE
			masking = false
		}

		launch {

		}

		routing {
			get("/") {
				call.respondText (
					this::class.java.classLoader.getResource("index.html")!!.readText(),
					ContentType.Text.Html
				)
			}
			static("/") {
				resources("")
			}
			route(Message.path) {
				get {
					call.respond(messages)
				}
				post {
					messages += call.receive<Message>()
					call.respond(HttpStatusCode.OK)
				}
			}
			webSocket("/ws/send") {
				val thisConnection = Connection(this)
				connections += thisConnection
				try {
					for (frame in incoming) {
						frame as? Frame.Text ?: continue
						val receivedText = frame.readText()
						println("Received: $receivedText")
						connections.forEach {
							it.session.send(receivedText)
						}
					}
				} catch (e: Exception) {
					println(e.localizedMessage)
				} finally {
					connections -= thisConnection
				}
			}
		}
	}.start(true)
    }
`

Note that I'm not using the whole fritz2. I'm just using websockets, since I could not find another way to use it in Kotlin/JS.
I am using `implementation("dev.fritz2:components:0.11.1")`

Thanks for the support !

**Comment by jamowei** [comment]
Hi, if you using fritz2 only for performing a websocket communication, you should checkout [ktor-client](https://ktor.io/docs/websocket-client.html). I think that this fits better your need. Otherwise I would recommend you to use only the `implementation("dev.fritz2:core:0.11.1")` dependecy instead. It contains much less and the websocket API. We never tried our websocket API with other Kotlin/JS Frameworks like React etc. That's why it is hard for us to reproduce your problem. In fritz2 you have to handle the websocket messages in a `Handler` of a `Store` and that works and is tested. So your approach in contrast is not the fritz2-way of handling websocket connection...

**Comment by jamowei** [comment]
I can also see in your code snipped that there is no message send from the server to the client activly. That is why you don't receive a message on client-side. You should try to call the `send()` function on the session and then your server should anwser this request and you should see a log message.

**Comment by Toumani** [comment]
I tried `implementation("dev.fritz2:core:0.11.1")` and the result was the same. I finally end up with using org.w3c.dom.WebSocket with worked perfectly fine for my purpose. Am just trying to have a basic understanding of the KMM platform before jumping into any framework. But sure enough I'll stick with fritz2 when I feel more comfortable with the whole thing. Thank you for your suggestions.

**Comment by Toumani** [comment]
> I can also see in your code snipped that there is no message send from the server to the client activly. That is why you don't receive a message on client-side. You should try to call the `send()` function on the client-side ws-session and then your server should anwser this message and then you should see message with the same content in you client log.

There is an event handler with sends a message to the server. I omit it focus on the actual point.
