### ISSUE TITLE
Extension Properties for generated lenses for simpler and shorter usage

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#497]
The current lenses generation only generates a Lens like L.Object.property for each property.

When using deeper class structures the Lenses have to be stacked with the "+" operator, which can be very long.

For example to create a Lens for `OuterObject.innerObject.element.name` we have to use something like:

    L.OuterObject.innerObject + L.InnerObject.element + L.Element.name

My suggestion would be, that the Fritz2 Lenses Annotation Processor additionally generates extension properties like:

    val <R> Lens<R, InnerObject>.element get() = this + L.InnerObject.element
    val <R> Lens<R, Element>.name get() = this + L.Element.name

so that

    L.OuterObject.innerObject.element.name
can be used

Similar to that extension properties for the lenses, Store and Inspector interfaces could be extended with:

    val Store<OuterObject>.innerObject get() = sub(L.OuterObject.innerObject)
    val Inspector<OuterObject>.innerObject get() = sub(L.OuterObject.innerObject)

to be able to use the following

    OuterObjectStore.innerObject.element // type: SubStore<*, Element>
    inspector.innerObject.element // type: Inspector<Element>
    

These extensions would simplify coding and make the resulting code much more readable.

**Comment by chausknecht** [comment]
The basice idea is great, but there are some difficulties that emerge from the new approach to model automated lenses as functions of the companion object: We simply cannot add some custom inner object to a data class! But that would be the most elegant and garatueed working solution I can imagine:
```kotlin
@lenses
data class Address(
    val id: Int,
    val street: String,
    // ...
)

@lenses
data class Person(
   val id: Int,
   // ...
   val address1: Address,
   val address2: Address
)
```
This would lead to name clashing in multiple ways:
1) Address and Person both own a property with name `id` -> we cannot lift the `Address.id` property as lense into the scope of the `Person`'s companion object!
2) There are two fields of type `Address` within `Person` -> we cannot lift their properties into the scope of `Person`'s companion object, as those names would disturb each other!

So the only solution I can imagine would be to add some prefix or suffix! But how to name it? And would this make API usage rather harder to read than the handcrafted ``Lens`` combinations.

**Comment by metin-kale-cf** [comment]
1) Lens-Class only has an "id"-Property, which could lead to a name clashing, which even does not throw a compile error. Because we have functions instead of properties, this name clash is also resolved, because functions and properties might have the same name in kotlin. get/set Functions have parameters, so a parameterless extension function is also no problem.

2) why should they disturb each other? the generated code would be
```
    fun <R> Lens<R, Person>.id() = this + Person.id()
    fun <R> Lens<R, Person>.address1() = this + Person.address1()
    fun <R> Lens<R, Person>.address2() = this + Person.address2()

    fun <R> Lens<R, Address>._id() = this + Address.id()
    fun <R> Lens<R, Address>.street() = this + Address.street()
```
the parameter name is important, and this is already unique. 

Usage would be: `SomeClass.person().address1().street()` or `SomeClass.person().address2().street()`

**Comment by chausknecht** [comment]
I think I get the idea and I like it!

But I totally dislike the `_id` name - what is that? When do you add an underscore? How does the user "know" this? What is the rule for naming like this?

Can you please provide some running example with some corner cases please? This would be the best to discuss the API and consequences.

**Comment by metin-kale-cf** [comment]
The "_id" was necessary in fritz0.13 because Lens-Class has an id-property, which would shadow the extension property.

I dont think we need this anymore, because fritz0.14 uses extension functions instead of variables. 
`    fun <R> Lens<R, Address>.id() = this + Address.id()`
would be fine in this case
