### ISSUE TITLE
server side rendering example?

### ISSUE THREAD

**Issue by x51** [jwstegemann/fritz2#499]
hey i want a server side rendering example of fritz2. can anyone help me to get this or had already implemented?

**Comment by chausknecht** [comment]
SSR is currently not directly supported by fritz2. Our focus still lies on improving and stabilizing our framework. So in the future it might be possible and even tempting to provide a built-in way directly within fritz2, but currently this is beyond our focus.

That said we are always open for proposals!

I think one would need to enable the DOM API usage within the server and find a way to setup all stores initially, serialize everything and send it bundled to the client, which then could put the DOM into the browser and restore the stores.

Does this answer your question? Or do you have some use case different to initial page setup?

**Comment by x51** [comment]
So can i integrate express server to  it with dom api.if it possible then any help for creating express server with kotlin/js?

**Comment by chausknecht** [comment]
I have no experience with express, so unfortunately I can't help you with it. I would assume that express is rather a fully fledged HTPP server framework. Are you shure it offers some DOM API? Besides: Don't you already have some server framework in place? If so I would rather look for ways to integrate some DOM API offering libs like jsdom and try to realize the proposed way with it.

Can you please give some more information about your overall intentions? Why do you neeed / want SSR?

**Comment by x51** [comment]
well, i wanna build ssr based static simple web pages(around 3 or 4) bcz of seo using kotlin/js. so i searched for this around web, nothing found yet, but i think first bundled into a SPA then use it through express server would be great idea but here i don't know how to write some kotlin code to do this using express server so i keep look around the web.

**Comment by x51** [comment]
one more thing i don't wanna write some code in javascript.

**Comment by chausknecht** [comment]
Imho fritz2 is not suited for your use case. fritz2 is focused on dynamic and reactive web pages, so primarely SPAs.

You are more or less looking for some static site generator. There are myridas available - so even if I don't know one, there should also be something available for kotlin I guess, if that is really important for you.

If you want to make your hands dirty, than have a look for [kotlinx.html](https://github.com/Kotlin/kotlinx.html), which enables type safe HTML generation. So armed with that, you can create your own bare metal solution if [jekyll](https://jekyllrb.com/) or [hugo](https://gohugo.io/) do not fit for you.

SSR for SPAs is rather some optimatzation tool as I said above. It can speed up initial delivery of a stateful SPA, so the UX enahances even if network speed is kinda slow or unstable. This increases even more, if the SPA can work offline for some user interactions. But this is not well suited for a priori designed static web pages!
