### ISSUE TITLE
Use diff-algorithm for classList / classMap

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#53]
The newly implemented algorithm to diff lists could be used for the class-attribute to add and remove single classes via `addClass` and `removeClass` to improve performance (?).

**Comment by jwstegemann** [comment]
I think this is not viable anymore since

- the browser will most probably to exactly this, when we reset the whole attribute
- complex styling can / should be done using the styling module instead

@jamowei What do you think? Please close if agree...

**Comment by jamowei** [comment]
I totally agree with you and close this issues.
