### ISSUE TITLE
Improve API documentation: https://api.fritz2.dev/ (dokka generated)

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#540]
We should try to add some version and date information to our API documentation. Currently it is impossible to know, which version is adressed! Also we only publish the documentation to our current release, it will add more trust to *see* the exact relation to the project's version.

![fritz2_dokka_missing_version](https://user-images.githubusercontent.com/70946811/139048435-69fe9ba3-5071-4482-855e-374141f94da8.png)

**Comment by jamowei** [comment]
Also in Dokka 1.6.10 no easy way to add the version to the title... 😔

**Comment by jwstegemann** [comment]
Still not possible in current Dokka version. Maybe some time in the future...
