### ISSUE TITLE
ClassCastException with keyup-event when pressing 'Return'

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#547]
I have the following code:

`                            keyups.map { it }.onEach { println(it) }.filter { it.keyCode == 13 }.map { it.target.asDynamic().value } handledby handler
`

to detect return key.

When typing normal characters i get a KeyboardEvent, no problems here. But as soon i press Return, i get a ClassCastException, because the Event is not of type KeyboardEvent.

There are some more Issues like this. Javascript seems not to be consistent with Event Types. A solution might be not to enforce specific event types and to always pass the type "Event". The actual event object is rarely used, so it would not be a problem to let the user check and cast the event to the desired type, if needed.

**Comment by chausknecht** [comment]
For handling keys you should strive for using the `key` extension method for `KeyboardEvents` (although this probably won't solve your problem!):
```kotlin
keyups.key().filter { it == Keys.Enter }
```
This is much better to read than a numerical code.

Can you please elaborate which browser led to this problem and which element?
We have already some code that handles the enter key, and this problem has never been reported. So maybe it is a special combination of browser and DOM tree?

**Comment by metin-kale-cf** [comment]
You are right, the problem seems to be on my side. 

The problem was with .map { it.target.asDynamic().value }, which returned a type of dynamic, which caused the exception in the handler.
