### ISSUE TITLE
Strange TypeAhead behaviour

### ISSUE THREAD

**Issue by metin-kale-cf** [jwstegemann/fritz2#549]
The typeAhead Component behaves quite strange and confusing in some situations. 

I tested the typeAhead in the Kitchensink, where the problems are also present:
![TypeAhead3](https://user-images.githubusercontent.com/84390402/143218706-06e8b225-6536-4233-bfe1-88b233352754.gif)

1. Missing suggestion, if word is fully typed (if i type "Java" fastly, i would think, there is no option Java, because it is not shown)
2. Missing/wrong suggestions when removing characters
3. No initial suggestions, but when the typeahead was used before, but is empty, old suggestions will be shown
4. If i type fastly and stop, no suggestions will be shown. I have to type the last character after a delay, to trigger the suggesions

**Comment by chausknecht** [comment]
The current approach based upon dynamic [datalist](https://developer.mozilla.org/de/docs/Web/HTML/Element/datalist) entries simply does not work! It seems to me that the HTML standard has never meant this to change dynamically.

There are also similar [problems](https://bugs.webkit.org/show_bug.cgi?id=201121) with Safari engine, which we cannot fix ourselves.

We must definitly strive for another approach with a custom solution based upon some popup area that shows the options.

So I believe we will not fix this for the current approach.
