### ISSUE TITLE
datatable broken in safari & ios

### ISSUE THREAD

**Issue by jillesvangurp** [jwstegemann/fritz2#551]
**Describe the bug**

I have a simple application with a data table. It misrenders in safari. The table rows are appearing next to the header instead of below.

**To Reproduce**

```kotlin
data class Foo(val foo:String)

render("#target") {
        val s = storeOf(listOf(Foo("foo"), Foo("bar"), Foo("foobar")))
        val fooLens = buildLens<Foo, String>(
            id = "fooCol",
            getter = { it.foo },
            setter = { old, v -> old.copy(foo = v) })
        val selected = storeOf<Foo?>(null)
        s.data.render {
            dataTable(rows = s, rowIdProvider = { it.foo }, selection = selected) {
                columns() {
                    column(title = "Foo") {
                        lens(fooLens)
                    }
                }
            }
        }
}

```

**Expected behavior**

rows appear below each other

**Screenshots**

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/819187/143845097-bb6842cf-abd2-4c53-8b6e-e603acbf24de.png">

**Desktop (please complete the following information):**
 - MacOS /  IOS
 - Safari
 - Fritz 0.13

**Comment by chausknecht** [comment]
Just ot be sure you do not build this upon an old version of our [template](https://github.com/jwstegemann/fritz2-template): Have you a base that includes this [PR](https://github.com/jwstegemann/fritz2-template/pull/7)? (It improves the template HTML file)

I still remember that his has fixed lots of rendering issues...

**Comment by jillesvangurp** [comment]
I am using the fritz2 0.13 release. Do you have an easy way to upgrade to that without custom builds? I'm guessing I'll need both the gradle plugin and the library.

**Comment by chausknecht** [comment]
Just check out the current version of our template project. This should work with fritz 0.13 out of the box. Just add your table demo into the `add.kt` and `component` module to the `build.gradle.kt` and try it.

I am quite sure the adaptions to the `index.html` has corrected also layout errors with the data table MacOS...

**Comment by jillesvangurp** [comment]
Thanks, I played a bit with this to figure out what causes this. At first glance all the differences are trivial. So, I narrowed it down by trying things one by one.

It turns out that adding this at the top of our index.html fixes things:

```
<!doctype html>
```

Safari apparently goes into some legacy/quirks mode without that: https://hsivonen.fi/doctype/

Never knew that was a thing. Probably worth documenting.

**Comment by chausknecht** [comment]
> Probably worth documenting.
Good idea - but how and where exactly? Not sure a comment right above the document initialization is allowed and won't break anything... below and the relation might be unclear? Also this would appear inside every delivered HTML document.

I can imagine exposing this to the data table component within our KitchenSink, but this bug also affects other components iirc - but which exactly?

Hard :-D

**Comment by jillesvangurp** [comment]
Maybe just document this in the readme of the component library. Something like :

Safari's quirk mode has several known issues with Fritz2 components. Fritz2 components relies on html5 and css standard behavior. To prevent browsers such as Safari from engaging their quirks mode, put `<!doctype html>` at the top of your `index.html`.
