### ISSUE TITLE
Define attributes that are static by definition as parameter at factory-method

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#56]
Attributes that will not change over time should be offered as an optional parameter  of the factory-method of the element.

This implemented at `label` for the `for`-attribute with #55.

The issue should collect all the attributes that should be handled this way to change implementation later in one row.

**Comment by jwstegemann** [comment]
input.type

**Comment by hpehl** [comment]
a.target

**Comment by hpehl** [comment]
> input.type

This is pretty important. I've noticed visual flickering when rendering a page with lots of 

```kotlin
render {
    input {
        type = const("checkbox")
    }
}
```

After replacing this with 

```kotlin
render {
    input {
        domNode.type = "checkbox"
    }
}
```

there's no more flickering.

**Comment by jwstegemann** [comment]
In 0.8 we changed handling attributes by using overridden methods to set, therefore this is not necessary anymore for performance reasons.
In addition it is important for all factory-functions for tags to have the same signature for the new styling- and components dsl.
