### ISSUE TITLE
can no longer invoke handlers as methods

### ISSUE THREAD

**Issue by jillesvangurp** [jwstegemann/fritz2#656]
**Describe the bug**

I used to be able to update stores with a value. But this no longer seems to work as documented in Rc1 / as it used to.

for example:

```kotlin
val myStore = storeOf(1.0)

....

// inside some event handler
myStore.update(2.0)
```

The same applies to custom handlers. So, the [Connecting stores to each other](https://www.fritz2.dev/docs/state/) no longer seems to be correct.

Is this intentional? If so, what is the correct way of doing this now? I have a lot of code where I just want to put the value of some response or action in a store, so invoking update directly is something I need.

**Comment by chausknecht** [comment]
Can you please show us a minimal running example (best based upon our [fritz2-template](https://github.com/jwstegemann/fritz2-template)-project)?

I have implemented this one and tried it with the RC1:
```kotlin
fun main() {

    val someStore = storeOf("foo")

    val otherStore = object : RootStore<String>("") {
        val updateOther = handle { state ->
            someStore.update("bar")
            state
        }
    }

    render {
        p {
            +"This site uses: "
            b { someStore.data.renderText() }
        }

        button {
            +"Change by Other"
            clicks.map {  } handledBy otherStore.updateOther
        }
    }
}
```

It works like a charm :-)

So not sure whether you might have hit a corner case?

**Comment by jillesvangurp** [comment]
Hey your sample indeed works. But mine somehow doesn't:

It says reference not found on the update function. The same code worked fine with 0.14

``` kotlin
val compassDirectionStore = storeOf(-1.0)


val isIOS by lazy {
    val re = "(iPod|iPhone|iPad)".toRegex()
    val ua = window.navigator.userAgent
    (re.find(ua) != null && ua.contains("AppleWebKit"))
}

fun registerCompassHandler() {
    val handler = object : EventListener {
        override fun handleEvent(event: dynamic) {
            console.log(event)
            val dir = if(isIOS) {
                event.webkitCompassHeading as Double
            } else {
                abs(event.alpha as Double - 360.0)
            }
            compassDirectionStore.update(dir)
        }
    }
    if(isIOS) {
        window.addEventListener("deviceorientation", handler, true)
    } else {
        window.addEventListener("deviceorientationabsolute", handler, true)
    }
}

fun RenderContext.compassIndicator() {
    h1 {
        +"Compass"
    }
    compassDirectionStore.data.render {
        p {
            if (it >= 0) {
                +"$it degrees"
            } else {
                +"Not receiving compass  updates"
            }
        }
    }
}

fun main() {
    registerCompassHandler()
    render("#target") {
        compassIndicator()
    }
}
```

**Comment by jwstegemann** [comment]
This indeed changed with PR #622 . It was necessary, because you need a valid job, where you call it, so the `invoke` on a handler is available inside a `Store` or a `RenderContext`. In most cases (like our tests, demos and examples) there will be no need to call it from another place. But it is definitely wrong in the docs right now and is missing in the release notes as a breaking change. We will fix this asap.

**Comment by jwstegemann** [comment]
Please allow me to suggest a maybe more fritz2-like way to do what (when I got it right) want to do with your code above:

```kotlin
fun main() {
    val compassDirectionStore = storeOf(-1.0)

    val orientations =  Window.subscribe<dynamic>(if(isIOS) "deviceorientation" else "deviceorientationabsolute")

    orientations.map {event ->
        if(isIOS) event.webkitCompassHeading as Double
        else abs(event.alpha as Double - 360.0)
    } handledBy compassDirectionStore.update

    render("#target") {
        h1 {
            +"Compass"
        }
        compassDirectionStore.data.render {
            p {
                if (it >= 0) {
                    +"$it degrees"
                } else {
                    +"Not receiving compass  updates"
                }
            }
        }
    }
}
```
