### ISSUE TITLE
maintenance release for 0.14 branch with updated dependencies 

### ISSUE THREAD

**Issue by jillesvangurp** [jwstegemann/fritz2#659]
It looks like switching to 1.0 is going to be a major project for us due to the deprecation of the current component library. Realistically, we won't be able to do this shortly because we have other priorities right now. Would it be possible to do a maintenance release for the 0.14 branch with updated dependencies? We are kind of blocked on updating a lot of our internal dependency because of this. 

I'd be happy to do a pull request for this of course.

**Comment by chausknecht** [comment]
Do you mean Kotlin itself as dependency?

**Comment by jillesvangurp** [comment]
yes, we want kotlin 1.7.10. Currently the lenses ksp dependency makes this impossible. So, I would like to create a new version of the 0.14 branch with more recent dependencies.

**Comment by chausknecht** [comment]
Sounds quite reasonable to me!

We would appreciate if you could create a fitting PR based upon the 0.14-branch. As this is vacation time we are currently quite limited with our capacities, so it would take us probably longer to take care of this wish.

Consider this [comment](https://github.com/jwstegemann/fritz2/pull/646#issuecomment-1177670049) for testing the dependencies, if you will come up with a solution.

Thx again for your interest in fritz2 and your pleasent help!

**Comment by jillesvangurp** [comment]
I understand, I'll try to get a PR together over the next few weeks. Quite busy over here as well.

**Comment by jillesvangurp** [comment]
I created a pull request for this.

**Comment by jillesvangurp** [comment]
@chausknecht can you do a maven release for this branch as well?

**Comment by chausknecht** [comment]
I just wait for the approval of my teammates. As some are on holidays it takes more time than usual ;-)

But as you might have seen all is prepared to release a 0.14.4!

**Comment by jillesvangurp** [comment]
Great!
