### ISSUE TITLE
Support for Kotlin `Iterable` interface instead of `List`

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#676]
We should provide support for the more general interface `Iterable` instead for specific `List` class, cause the you can also render e.g. a `Set` too.

**Comment by chausknecht** [comment]
Sounds like a good idea - but do we rely upon either (a) the specific algorithmic performance or (b) some specific API from the ``list`` class? (Meyer-Diff maybe?)

Another important aspect is the concept of stable ordering: a [Set](https://kotlinlang.org/docs/collections-overview.html#set) does not guarantee any order at all. So how would we identify the same items without ``idProvider``?

**Comment by jamowei** [comment]
After some discussion on that topic, we decided that this feature is not needed, because we can't render a collection which is not index-based or ordered. This is in Kotlin guaranteed by the `List` interface which we currently use.
