### ISSUE TITLE
Rework Closing of Headless Toast by ESC key to Event Capturing

### ISSUE THREAD

**Issue by ghost** [jwstegemann/fritz2#713]
Currently the headless toast component (see PR #701) enables one to close the toasts by ESC-key.
This conflicts with other components (`PopUpPanel` based ones) which also register their closing on the window level.

If event capturing is available in fritz2, we should use the former for the ESC-key event handling. This way we can then stop the propagation, if there was at least one toast to close. This way all other components would not react.

depends on #552

**Comment by Lysander** [comment]
As [ARIA-Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alert/) recommend, there should no Keyboard-Interaction at all for toasts.

So we should not implement this!
