### ISSUE TITLE
Streamline and unite various store derivating APIs like sub, orDefault and format

### ISSUE THREAD

**Issue by chausknecht** [jwstegemann/fritz2#725]
Starts with Jan's comment :-)

**Comment by jamowei** [comment]
After some discussion on this topic, we came up with the following API improvement:
### Stores mapping
| current | new |
|---|---|
| Store\<P\>.sub(lens: Lens<P, T>): Store\<T\> | Store\<P\>.**map**(lens: Lens<P, T>): Store\<T\> |
| Store<P?>.sub(lens: Lens<P & Any, T>): Store\<T\> | Store\<P?\>.**map**(lens: Lens<P & Any, T>): Store\<T\> |
| Store<List\<T\>>.sub(element: T, idProvider): Store\<T\> | Store<List\<T\>>.**mapByElement**(element: T, idProvider): Store\<T\> |
| Store<List\<T\>>.sub(index: Int): Store\<T\> | Store<List\<T\>>.**mapByIndex**(index: Int): Store\<T\> |
| Store<Map\<K, V\>>.sub(key: K): Store\<V\> | Store<Map\<K, V\>>.**mapByKey**(key: K): Store\<V\> |
| Store<T?>.orDefault(default: T): Store\<T\> | Store<T?>.**mapNull**(default: T): Store\<T\> |
| MapRouter.sub(key: String): Store\<String\> | MapRouter.**mapByKey**(key: String): Store\<String\> |

### Lens creation
| **current** | **new** |
|---|---|
| lens(id: String, getter: (P) -> T, setter: (P, T) -> P): Lens<P, T> | **lensOf**(getter: (P) -> T, setter: (P, T) -> P, **id: String = ""**): Lens<P, T> |
| format(parse: (String) -> P, format: (P) -> String): Lens<P, String> | use lensOf() instead |
| lensOf(element: T, idProvider: IdProvider<T, I>): Lens<List<T>, T> | **lensForElement**(element: T, idProvider: IdProvider<T, I>): Lens<List<T>, T> |
| lensOf(index: Int): Lens<List<T>, T> | **lensForElement**(index: Int): Lens<List<T>, T> |
| lensOf(key: K): Lens<Map<K, V>, V> | **lensForElement**(key: K): Lens<Map<K, V>, V> |
| defaultLens(id: String, default: T): Lens<T?, T> | not public available anymore |

### Lens mapping
| **current** | **new** |
|---|---|
| Lens<P, T>.toNullableLens(): Lens<P?, T> | Lens<P, T>.**withNullParent()**: Lens<P?, T> |
| Lens<P, T>.asString(): Lens<P, String> | Lens<P, T>.asString(): Lens<P, String> |
| Lens<P, T?>.asString(): Lens<P, String> | Lens<P, T?>.asString(): Lens<P, String> |
| Lens<P, T>.plus(other: Lens<T, X>): Lens<P, X> | Lens<P, T>.plus(other: Lens<T, X>): Lens<P, X> |
