### ISSUE TITLE
Easier documentation on CSS import

### ISSUE THREAD

**Issue by violabs** [jwstegemann/fritz2#745]
I am having a hard time finding information on where exactly to add css and how to get top level or components to connect with it.

Perhaps there is a simple place to put a `Styling` example page or, if it exists, have it in the getting started as a link.

**Comment by chausknecht** [comment]
As fritz2 is totally agnostic of Styling, there is no generic solution and thus I cannot imagine, how to document this.

For your own CSS classes, you can just add them in the `index.html` file or a separate CSS-file within `src/jsMain/resources` folder.

For tailwindcss we offer a dedicated [template](https://github.com/jwstegemann/fritz2-tailwind-template) btw - this should work out of the box.

For embedding bootstrap, just have a look at our examples. Most of those use bootstrap, so it should be easy to integrate into your template html file. Here is the [link](https://github.com/jwstegemann/fritz2/blob/master/examples/gettingstarted/src/jsMain/resources/index.html) to the getting started example.

Does this solve your problems?

If not, can you specify your problem?

**Comment by violabs** [comment]
Hello! Thank you for your response.

All of the documentation was great! I think I started down a rabbit hole of excitement, and started on some tutorial document. Then as I wanted to expand on that I looked at other documentation and tried to add the Tailwind CSS stuff. Adding it separately didn't go as planned, so I just reverted to plain CSS.

It was easy enough to add to the index (great suggestion), and I figured putting them in resources would work due to past JSP stuff, but I think if I didn't have that knowledge it would be harder to find out.

I think just a general location anywhere that addresses the CSS agnostic stance, but the "known" solutions to adding css.

I was trying to add clarity UI, but it requires javascript to work full and I gave up since I want to actually learn the framework over configuration. This is an aside, but that was what led me to try to figure out how exactly gradle compiles external css and js.

**Comment by violabs** [comment]
After a bit of trial and error I was able to get the tailwind css to work. Works great so far (still a bit of a learning curve but sure beats css direct).

On a separate note, I couldn't get multiplatform to play nice with fritz2 + springboot. I kept having gradle issues and other import problems with IntelliJ. I ended up just doing separate projects (non multiplatform for now since that took 2 days to troubleshoot).

You can close it if you want - still would be nice to have a dedicated spot about css and where the entry points are (even if it just points back to kotlin JS). It could also have entry point info on additional js file (I haven't started to look how and don't need to yet).
