### ISSUE TITLE
Origin of the name

### ISSUE THREAD

**Issue by EndzeitBegins** [jwstegemann/fritz2#75]
While reading through the documentation I was wondering what the project name stands for?

Is it an acronym?
Was there a fritz (1)? If so, what happened to it? 

I would love to see one or two sentences about this in the documentation.

The project looks very promising, keep up the good work!

**Comment by EvaBS** [comment]
Hi, thank you for your comment and suggestion!

Fritz2 actually has two meanings for us. For our project name, we were looking for something to connect our own lifes and St. Peterburg (Kotlin is an island in its proximity), and we came across Friedrich II. It was shortened to Fritz2 - so technically, there was Fritz1, but not as an API 😊 

The second meaning is personal and also connects to the pipes in our logo – Fritz was Jens‘ father’s name who had a huge impact on his life. He was a plumber.
