### ISSUE TITLE
Add documentation for sub-routes or implement ability to have sub routes.

### ISSUE THREAD

**Issue by violabs** [jwstegemann/fritz2#756]
Update the routing documents to show how to do routes like `dashboard/list`. Currently I have an implementation of:

```kotlin
val router = routerOf("dashboard")

val secondRouter = routerOf("list")

render {
    router.data.render { top ->
        when(top) {
            "dashboard" -> div {
                secondRouter.data.render { inner ->
                    when (inner) {
                        "list" -> div { +"Inner" }
                    }
                }
            }
        }
    }
}
```

My implementation has routes in sub components. Not sure if this just isn't implemented, or if it is not documented.

I have also tried `routerOf("dashboard/list")` and that seems to chop off the `/`.

Also, is there a best place to ask question other than making a issue ticket?

**Comment by violabs** [comment]
Added clarification `routerOf("dashboard/list")` works but makes the url `#dashboard%2Froute`

**Comment by chausknecht** [comment]
> Also, is there a best place to ask question other than making a issue ticket?

No, that is totally fine :-)

We have also some sub-channel inside the Kotlin Slack - but I have to admit, that we rarely log in there. (I do not have any other use case for slack...)

> My implementation has routes in sub components. Not sure if this just isn't implemented, or if it is not documented.

I have to admit, that it kinda surprises me, that someone wants segmenting within hash routing too.

In the end it is possible and you have found a solution, even though I would try another approach: You can implement your own `Route<T>` as described in the documentation. So I would try to model the segmentation within a custom type, that accepts a finite (fields) or arbitrary set (list) of segments depending on your needs. The serialization should then insert the slashes, while deserialization splits upon those.

Does this help you?

**Comment by violabs** [comment]
Sounds great; I appreciate it!

I come from a background of Angular 2-14 and they have a sort of robust router, more overkill than needed, so I was trying to utilize it like that. Not sure if it is something useful but they have a sort of way to also have sub route displays within displays. I don't necessarily need that since it is a weird (and kind of confusing setup).

Ohh yeah. Custom route would be great - good suggestion.

I currently implement something such as:

## Router Info
```kotlin
object Routes {
    const val HOME = "home"

    object Docker {
        object Service {
            const val DASHBOARD = "docker-service"
            const val LIST = "docker-service-list"
            const val FORM = "docker-service-form"
        }

        object Compose {
            const val DASHBOARD = "docker-compose"
            const val LIST = "docker-compose-list"
            const val FORM = "docker-compose-form"
        }
    }
}

val ROUTER = routerOf(Routes.HOME)
```

## App Level Route

```kotlin
ROUTER.data.render { site ->
    when {
        site == Routes.HOME -> homeComponent {  }
        site.contains(Routes.Docker.Service.DASHBOARD) -> DockerServiceDashboard.render(this)
        site.contains(Routes.Docker.Compose.DASHBOARD) -> DockerComposeDashboard.render(this)
        else -> div { +"IDK" }
    }
}
```

## Rendered
```kotlin
object DockerComposeDashboard {
    private val routeMap: Map<String, (RenderContext) -> Any> = mapOf(
        Routes.Docker.Compose.FORM to DockerComposeForm::render,
        Routes.Docker.Compose.LIST to DockerComposeList::render,
        Routes.Docker.Compose.DASHBOARD to DockerComposeForm::render
    )

    fun render(context: RenderContext) = context.div {
        nav(m.b.n4 + space.x.n4) {
            button(SharedStyle.buttonStyle) {
                +"Form"
                clicks.map { Routes.Docker.Compose.FORM } handledBy ROUTER.navTo
            }

            button(SharedStyle.buttonStyle) {
                +"List"
                clicks.map { Routes.Docker.Compose.LIST } handledBy ROUTER.navTo
            }
        }

        ROUTER.data.render {
            routeMap[it]?.invoke(this)
        }
    }
}
```

I am still trying to play around with your framework, so finding good ways to do it is fun and a challenge. This should work for now, but I do want to try your suggestion in the future.

**Comment by chausknecht** [comment]
So I assume we could close this one?

**Comment by violabs** [comment]
Yeah. At least on my end I don't need the solution then.
