### ISSUE TITLE
Use Optics from Arrow?

### ISSUE THREAD

**Issue by serras** [jwstegemann/fritz2#779]
Hi, I'm the main maintainer of [Arrow Optics](https://arrow-kt.io/learn/immutable-data/) and the corresponding plug-in. I've been playing with fritz2 for personal projects, and one of the things that I was curious about is why fritz2 has its's own `@Lenses` annotation, instead of maybe reusing Arrow's.

From the Arrow side we would be extremely happy if a project like fritz2 would consider Arrow 😄  I'm happy to talk about any feature that may be missing from Arrow that would be required for fritz2.

**Comment by Lysander** [comment]
Hi :-)

I became member of the fritz2 team after the decision has been already taken, not to rely on Arrow. Nevertheless I will try to answer your question:

Afair the main reason was to keep the dependencies of the core library as minimal as possible. Also it might be possible, that the API of Arrow's Lenses was not stable yet at this time?

I also remember, that we internally have discussed to investigate a way to use Arrow in fritz2 after the 1.0 release.

I think @jwstegemann or @jamowei could answer this ultimatively :-)

**Comment by serras** [comment]
Makes sense. I’m working on a small `arrow-fritz2` module, hopefully I’ll get to publish it by the end of the week.

**Comment by Lysander** [comment]
Sounds very cool!

Please ping us then!
