### ISSUE TITLE
Migrate GitHub workflows to github-workflows-kt

### ISSUE THREAD

**Issue by jamowei** [jwstegemann/fritz2#814]
Migrate GitHub workflows to https://typesafegithub.github.io/github-workflows-kt/

**Comment by Lysander** [comment]
Are we sure, that we want do do that?

Despite the advantages, we loose the ability to "copy & paste" snippets from the web. Imho that is more important, as we do not touch configuration that often and are not really digging deep inside such tasks.

**Comment by Lysander** [comment]
We have decided to stay with the default github devops language.
