### ISSUE TITLE
Fritz2 1.0-RC15 is not available on maven central

### ISSUE THREAD

**Issue by MrAolen** [jwstegemann/fritz2#846]
Hello,
 
 I have a question. Fritz2 has been released with a new version : [1.0-RC15](https://github.com/jwstegemann/fritz2/releases/tag/v1.0-RC15), but it does not seem to be published on maven central, is that normal ? 
 
 Thanks for your help.

**Comment by jamowei** [comment]
Hi, at the moment we had some trouble to publish our new version to MavenCentral. But we are working on it! Hopefully we will fix it today,

**Comment by jamowei** [comment]
We found out that this is a common problem with Gradle and used the workaround described here: https://github.com/gradle/gradle/issues/26091
