### ISSUE TITLE
Missing Documentation On Using KotlinX Serialization With Remote Calls

### ISSUE THREAD

**Issue by napperley** [jwstegemann/fritz2#86]
In the Fritz2 documentation it doesn't cover how to use KotlinX Serialization with [remote calls](https://docs.fritz2.dev/RemoteCalls.html). Also there is no guidance on how data modelling is handled with remote calls when using KotlinX Serialization.

**Comment by jamowei** [comment]
Currently I'm working on an full-stack example of using fritz2 within an spring boot application. All is written with Kotlin and I will use the multiplatform kotlinx.serialization libary. After this we will extend our documentation on that :)

**Comment by jamowei** [comment]
We implemented a small abstraction for transferring data between client and different endpoints which we call "Repositories".
Check out our documentation on that [here](https://docs.fritz2.dev/Repositories.html).
You can see this API in action in some of our full-stack-examples (meant above).
- [fritz2-ktor-todomvc](https://github.com/jamowei/fritz2-ktor-todomvc)
- [fritz2-spring-todomvc](https://github.com/jamowei/fritz2-spring-todomvc)

```kotlin
object ToDoSerializer : Serializer<ToDo, String> {
    override fun read(msg: String): ToDo = Json.decodeFromString(ToDo.serializer(), msg)
    override fun readList(msg: String): List<ToDo> = Json.decodeFromString(ListSerializer(ToDo.serializer()), msg)
    override fun write(item: ToDo): String = Json.encodeToString(ToDo.serializer(), item)
    override fun writeList(items: List<ToDo>): String = Json.encodeToString(ListSerializer(ToDo.serializer()), items)
}
```

**Hint**: In upcoming version 0.9 we simplified the API a bit, so when this version gets released view our release-notes for details on that. We also try to update our examples accordingly.

Reopen if that don't fit your needs.
