### ISSUE TITLE
Lens extensions of generic classes are generated incorrectly

### ISSUE THREAD

**Issue by henryB99** [jwstegemann/fritz2#868]
**Describe the bug**
The lenses annotation processor generates the extension functions (which are convenient because they allow us to chain lenses with dot notation) generated invalid code, if the annotated class has a generic type parameter. We have test cases for this, but they are implemented incorrectly to expect the faulty code.

**To Reproduce**
1. Create a data class with a type parameter, annotate it with `@Lenses` and add the obligatory companion object (note that `bar` **does not** have to be generic for this to fail), i.e.
```kotlin
@Lenses data class Foo<T>(val bar: Any) { companion object }
``` 
2. Run the `assemble` Gradle task (to generate the lenses, any task that depends on the actual KSP task should be enough, but running `assemble` also tries to compile the code and ensures that you run into an error).
3. Look into the Gradle log. It should say something like this:
```
e: file:///.../FooLenses.kt:13:77 No value passed for parameter 'bar'
```
```
e: file:///.../FooLenses.kt:13:84 Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun <T> Foo.Companion.bar(): Lens<Foo<TypeVariable(T)>, TypeVariable(T)> defined in ... in file FooLenses.kt
public fun <PARENT, T> Lens<TypeVariable(PARENT), Foo<TypeVariable(T)>>.bar(): Lens<TypeVariable(PARENT), TypeVariable(T)> defined in ... in file FooLenses.kt
```
4. Open the file mentioned by the error message and you should see something like this:
```kotlin
public fun <PARENT, T> Lens<PARENT, Foo<T>>.bar(): Lens<PARENT, T> = this + Foo<T>.bar()
                                                                         // ^^^^^^^^^^^^
                                                                         // This is the actual error
```

**Expected behavior**
A type parameter at that place does not make sense, the annotation processor probably puts the class name instead of the companion object there, which is fine as long as no generics are involved. Removing the type parameter fixes the issue as far as i was able to verify.

**Desktop (please complete the following information):**
This affects all platforms.

**Smartphone (please complete the following information):**
This affects all devices.

**Comment by Lysander** [comment]
Thank you for your feedback and the detailed description. This should be quite easy to fix imho.
