### ISSUE TITLE
Move `whenever` function out of `Tag` interface

### ISSUE THREAD

**Issue by haukesomm** [jwstegemann/fritz2#873]
Currently, the convenience functions `T.whenever(Boolean): Flow<T?>` and `Flow<T>.whenever(Boolean): Flow<T?>` are defined inside the `Tag` interface and are thus limited to such contexts. They do not rely on any `Tag`-specific apis, though, and only act as shorthand functions for vanilla `Flow` operations.

Thus, I would like to propose lifting them out of the interface so they can be used in other places as well.

**Comment by Lysander** [comment]
Good idea - would also not be API breaking, as current usages wont be affected.
