### ISSUE TITLE
Example with event-debouncing

### ISSUE THREAD

**Issue by jwstegemann** [jwstegemann/fritz2#88]
Create an example that debounces events fired:
Use a range input to define the debouncing-interval and offer a button that uses this interval debouncing it's clicks.

**Comment by Lysander** [comment]
As [debounce](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html) is part of Kotlin's `Flow`-API, imho there is no need for a dedicated example. You can just apply this on any `Listener` (aka event-flow) as needed.

We do not have dedicated examples for other `Flow` related functions either.
