### ISSUE TITLE
Chat, Forum or ML

### ISSUE THREAD

**Issue by hpehl** [jwstegemann/fritz2#89]
I'm new to Kotlin/JS and came across fritz2 recently. I'm really impressed! It's focused, fast and well designed. Great job!

After having played with it for a while now and after writing first real code [1], I have questions here and there. So I'm wondering if there's something like a chat, mailing list or forum?

Would love to have a chat with the authors and users of fritz2, if that's feasible.

[1] I'm (re)writing [halOS](https://github.com/hal/halos-console/) from using Kotlin HTML DSL to fritz2.

**Comment by jwstegemann** [comment]
Great to hear that. 

We have set up a [slack-channel](https://fritz2workspace.slack.com/) (please mail us to info@fritz2.dev to get invited) and a server to chat on [Discord](https://discord.gg/uCE28w). Choose whatever you like...

**Comment by jamowei** [comment]
we have also added two new badges on our README.md with the corresponding links.

**Comment by jamowei** [comment]
We use the **#fritz2** channel in the official kotlinlang slack right now. See https://github.com/jwstegemann/fritz2/issues/286
