### ISSUE TITLE
Headless combo box's KDoc references wrong pages in the online documentation

### ISSUE THREAD

**Issue by haukesomm** [jwstegemann/fritz2#904]
Some KDoc comments in the headless combo box still reference the list box's online documentation and need to be revised.

Edit: The API-Sketch may also need to be revised as there may some minor inconsistencies with the actual API.

**Comment by odoyhaha** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by haukesomm** [comment]
Locked conversation due to spam
