### ISSUE TITLE
Combobox goes into a loop when setting the value store to null

### ISSUE THREAD

**Issue by rm3dom** [jwstegemann/fritz2#912]
**Describe the bug**

Getting a loop when setting the store to null after a selection:

```
            val addStore = storeOf<ExportItem?>(null)
            addStore.data.handledBy { item ->
                if (item != null) {
                    selectedStore.update {
                        it + item
                    }
                    //Setting the store to null here after a selection to clear the input / selection
                    addStore.update(null)
                }
            }
            
           combobox<T> {
               items(items)
               value(selectedStore)
               //Manual selection is not helping.
               selectionStrategy.manual()
          .....
```
Video here:

[Screencast from 2024-10-29 14-35-58.webm](https://github.com/user-attachments/assets/6968138d-3701-4f05-b778-9fa85323968e)

If the issue is not immediately obvious, I will try to make a sample application and put it on github when I have some spare time.

**Expected behavior**

Expect the input to be cleared, the user has to search / type again to make a selection.

**Desktop (please complete the following information):**
 - Latest Chrome and Firefox on Linux

**Additional context**

Using the latest Fritz from main commit 2f1868cb9b0eafdc4b91f9fe14f77ee24bfe4241 (HEAD)

**Comment by Lysander** [comment]
I must admit, that we might have not ever tested reactively adding or removing items.
Thx for your report!

A stand alone example would be nice of course :-)

**Comment by rm3dom** [comment]
Thank you for the quick response.

I created an example of what I am doing here:

https://github.com/rm3dom/fritz2-examples

Hope this helps, as you will see the use case is a bit odd: Normally you would not clear the input, but I clear it to indicate to the user the action completed. 

I am slowly going through the combobox code (nice looking code btw) to try and understand its inner workings but there is a lot of abstraction going on so it will take a while.

**Comment by rm3dom** [comment]
I found the solution.

Changing `selectedStore.update( null )` to `selectedStore.enqueue { null }` solves the problem in the example I provided above.

Must have something to do with the order of things, doing the update in the event-loop gives everything a chance to update its state. Doing a synchronous update on a store while in a flow on its state does feel awkward.

You can close this issue. Thank you.

**Comment by Lysander** [comment]
Forget about the `enqueue` - this should rather be `protected` I assume...

I will try to anaylse your demo project.

**Comment by Lysander** [comment]
I have just fiddled around and found a solution:
```kotlin
        val add = selectionStore.handleAndEmit<String?, Unit> { state, new ->
            emit(Unit)
            selectedStore.update(null) // this is needed - why?
            if (new != null) state + new
            else state
        }

        val reset = selectedStore.handle<Unit> { _, _ ->
            null
        }

        selectedStore.data.filterNotNull() handledBy add
        // gets called everytime - but without resetting in emitting handler too, it wont work.
        add.onEach { console.log("reset called") } handledBy reset
```

I dont understand, why this works - and I consider this ugly ;-)

But perhaps it will fit as workaround for you right now.

**Comment by rm3dom** [comment]
Thank you.

There's definitely a race because launching a delay (100) and then set work
too.

I have multiple workarounds now, if I have time I'll dig into it. Unlikely
though.

**Comment by haukesomm** [comment]
Hey there! I looked into your issue and opened PR that changes the way the combobox's data-binding handles incoming values, preventing the above mentioned race-condition from occurring.

The fix will be included in RC20 and will also be backported to Kotlin 1.9.x based projects with a new RC19.3 patch release.

Hope this helps with your issue!

**Comment by rm3dom** [comment]
You the bomb. Thanks
