### ISSUE TITLE
Open tag classes

### ISSUE THREAD

**Issue by hpehl** [jwstegemann/fritz2#92]
This is a feature request to open the element classes like A, Li, Div et al for inheritance. 

I'm developing an UI library based on [PatternFly](https://www.patternfly.org/v4/). In order to integrate the PatternFly tags into the fritz2 DSL, I'd like to extend from the existing HTML tags like `Li` or `Div`.

**Comment by jamowei** [comment]
Hi, can you give us an concrete example for which you must extend the base HTML classes? Do you want to append additional attributes? This example would be great to make your intention clearer ;)

Did you already tried to open the HTML classes by your own? If yes did something din't work anymore?

**Comment by hpehl** [comment]
Normally I don't want to add new attributes, instead I would like to re-use the reactive attributes defined in the various HTML classes. For instance I implement a class for a button in [PatternFly](https://www.patternfly.org/v4/documentation/core/components/button) which roughly looks like that:

```kotlin
class Button(
    modifier: Set<String>,
    private val text: String? = null,
    private val iconClass: String? = null,
    private val iconRight: Boolean = false
) : PatternFlyTag<HTMLButtonElement>(ComponentType.Button, "button", "button".component()),
    WithText<HTMLButtonElement> {
    ...
}
```

and 

```kotlin
open class PatternFlyTag<out E : HTMLElement>(
    componentType: ComponentType,
    tagName: String,
    baseClass: String
) : Tag<E>(tagName, baseClass = baseClass) {
    ...
}
```

Instead of using `dev.fritz2.dom.Tag` as base class, I'd like to extend from `dev.fritz2.dom.html.Button`. That would give me all the reactive attributes like 

```kotlin
    var autofocus: Flow<Boolean> by AttributeDelegate
    var disabled: Flow<Boolean> by AttributeDelegate
    var name: Flow<String> by AttributeDelegate
    var type: Flow<String> by AttributeDelegate
    var value: Flow<String> by ValueAttributeDelegate
```

See https://github.com/hal/halos-console/blob/master/src/jsMain/kotlin/org/patternfly/Button.kt for the full source code.

**Comment by jamowei** [comment]
Hi Harald, did you tried this approach already?
```kotlin
// my own button component
// the receiver type of content function is Button instead of HtmlElements
fun HtmlElements.myButton(content: Button.() -> Unit): Button { 
    return button("btn my-btn") {
        name = const("my-button")
        domNode.onclick = {
            window.alert("My button was clicked!")
        }
        content()
    }
}

fun main() {
    render {
       myButton {
           autofocus = const(true)

           text("This is my button!")
       }
    }.mount("target")
}
```
The main important part here is that your receiver type in the `content` function parameter is a fritz2 `Button` and therefore all the standard html attributes which getting exposed by it are now available in the scope of this function. 
I haven't fully tried this approach but probably it can fit your needs...

**Comment by hpehl** [comment]
I've tried that approach and it normally works well. 

I have a few cases where I have my own tag class with custom attributes / methods. I'd like to extend from the standard tags and the receiver of the code block function is then my custom tag.

**Comment by jamowei** [comment]
Ok, can you give us a pull-request for that!? Then we will include it in our next fritz2 version. Thanks!

**Comment by hpehl** [comment]
Opened #104
